In [1]:
import pandas as pd
import numpy as np
import datetime
import duckdb
from abc import ABC, abstractmethod

In [2]:
## SUBSYSTEM FOR DATAWAREHOUSE RESOURCES CREATION
class DatawarehouseResourcesCreator(ABC):
    
    def __init__(self):
        pass

    def init_schemas(self):
        conn = duckdb.connect("insurance_case.db")
        conn.sql('CREATE SCHEMA IF NOT EXISTS governance')
        conn.sql('CREATE SCHEMA IF NOT EXISTS silver')
        conn.sql("CREATE SCHEMA IF NOT EXISTS gold")
        conn.close()
    
    def init_error_tables(self):
        conn = duckdb.connect("insurance_case.db")

        conn.sql("""
            CREATE OR REPLACE TABLE governance.fact_error_event (
                error_event_id INTEGER,
                batch_id INTEGER
            )
        """)

        conn.sql("""
            CREATE OR REPLACE TABLE governance.fact_error_event_detail (
                error_event_id INTEGER,
                batch_id INTEGER,
                screen_id INTEGER,	
                error_utc_timestamp TIMESTAMP,
                table_name VARCHAR, 
                column_name VARCHAR,
                record_identifier INTEGER,
                original_value VARCHAR,
                replaced_value VARCHAR,
                error_condition VARCHAR
            )
        """)

        conn.close()

In [3]:
#datawarehouse_resources_creator = DatawarehouseResourcesCreator()
#datawarehouse_resources_creator.init_schemas()
#datawarehouse_resources_creator.init_error_tables()

In [4]:
## SUBSYSTEM FOR SPECIAL DIMENSIONS MANAGEMENT
class AbstractSpecialDimensionManager:
    
    @abstractmethod
    def create_date_dimension(self):
        pass

    @abstractmethod
    def create_screen_dimension(self):
        pass

class SpecialDimensionManager(AbstractSpecialDimensionManager):

    def __init__(self):
        self.dim_date = None
        self.dim_screen = None

    def create_date_dimension(self):
        
        array_dates = pd.date_range(start='1900-01-01', end='1900-01-01')
        array_dates = array_dates.append(pd.date_range(start='1925-01-01', end='2029-12-31'))
        array_dates = array_dates.append(pd.date_range(start='2200-01-01', end='2200-01-01'))

        dim_date = pd.DataFrame({'date_id': array_dates, 'date': array_dates})
        dim_date['date_name'] = dim_date['date'].dt.strftime('%Y-%m-%d')

        dim_date['day'] = dim_date['date'].dt.day
        dim_date['month'] = dim_date['date'].dt.month
        dim_date['year'] = dim_date['date'].dt.year
        dim_date['day_of_week'] = dim_date['date'].dt.dayofweek + 1
        dim_date['day_name'] = dim_date['date'].dt.day_name()
        dim_date['month_name'] = dim_date['date'].dt.month_name()
        dim_date['quarter'] = dim_date['date'].dt.quarter
        dim_date['weekday_indicator'] = np.where(dim_date['day_of_week'].isin([6, 7]), 'Fin de Semana', 'Entre Semana')
        dim_date['week_of_year'] = dim_date['date'].dt.isocalendar().week
        dim_date['is_end_of_month'] = np.where(dim_date['date'] == dim_date['date'] + pd.offsets.MonthEnd(0), True, False)
        dim_date['is_end_of_quarter'] = np.where(dim_date['date'] == dim_date['date'] + pd.offsets.QuarterEnd(0), True, False)
        dim_date['is_end_of_year'] = np.where(dim_date['date'] == dim_date['date'] + pd.offsets.YearEnd(0), True, False)

        dim_date['date_id'] = dim_date['date_id'].dt.strftime('%Y%m%d').astype(int)
        dim_date.loc[dim_date['day_name'] == 'Monday', 'day_name'] = 'Lunes'
        dim_date.loc[dim_date['day_name'] == 'Tuesday', 'day_name'] = 'Martes'
        dim_date.loc[dim_date['day_name'] == 'Wednesday', 'day_name'] = 'Miércoles'
        dim_date.loc[dim_date['day_name'] == 'Thursday', 'day_name'] = 'Jueves'
        dim_date.loc[dim_date['day_name'] == 'Friday', 'day_name'] = 'Viernes'
        dim_date.loc[dim_date['day_name'] == 'Saturday', 'day_name'] = 'Sábado'
        dim_date.loc[dim_date['day_name'] == 'Sunday', 'day_name'] = 'Domingo'
        dim_date.loc[dim_date['month_name'] == 'January', 'month_name'] = 'Enero'
        dim_date.loc[dim_date['month_name'] == 'February', 'month_name'] = 'Febrero'
        dim_date.loc[dim_date['month_name'] == 'March', 'month_name'] = 'Marzo'
        dim_date.loc[dim_date['month_name'] == 'April', 'month_name'] = 'Abril'
        dim_date.loc[dim_date['month_name'] == 'May', 'month_name'] = 'Mayo'
        dim_date.loc[dim_date['month_name'] == 'June', 'month_name'] = 'Junio'
        dim_date.loc[dim_date['month_name'] == 'July', 'month_name'] = 'Julio'
        dim_date.loc[dim_date['month_name'] == 'August', 'month_name'] = 'Agosto'
        dim_date.loc[dim_date['month_name'] == 'September', 'month_name'] = 'Septiembre'
        dim_date.loc[dim_date['month_name'] == 'October', 'month_name'] = 'Octubre'
        dim_date.loc[dim_date['month_name'] == 'November', 'month_name'] = 'Noviembre'
        dim_date.loc[dim_date['month_name'] == 'December', 'month_name'] = 'Diciembre'

        dim_date['quarter_name'] = 'T' + dim_date['quarter'].astype(str)
        dim_date['year_month'] = dim_date['year'].astype(str) + '-' + dim_date['month'].astype(str).str.zfill(2)
        dim_date['quarter_year'] = dim_date['quarter_name'] + ' ' + dim_date['year'].astype(str)

        dim_date['holiday_indicator'] = 'No Festivo'
        dim_date.loc[dim_date['date'].isin(['2025-01-01', '2025-02-05', '2025-03-21', '2025-05-01',
                                            '2025-09-16', '2025-11-20', '2025-12-25']), 'holiday_indicator'] = 'Festivo'

        special_dates = pd.DataFrame({'date_id': [-1, -2],
                                      'date': [None, None],
                                      'date_name': ['No Aplica', 'No Disponible'],
                                      'day': [0, 0],
                                      'month': [0, 0],
                                      'year': [0, 0],
                                      'day_of_week': [0, 0],
                                      'day_name': ['No Aplica', 'No Disponible'],
                                      'month_name': ['No Aplica', 'No Disponible'],
                                      'quarter': [0, 0],
                                      'weekday_indicator': ['No Aplica', 'No Disponible'],
                                      'week_of_year': [0, 0],
                                      'is_end_of_month': [False, False],
                                      'is_end_of_quarter': [False, False],
                                      'is_end_of_year': [False, False],
                                      'quarter_name': ['No Aplica', 'No Disponible'],
                                      'year_month': ['0000-00', '0000-00'],
                                      'quarter_year': ['No Aplica', 'No Disponible'],
                                      'holiday_indicator': ['No Aplica', 'No Disponible']})

        self.dim_date = pd.concat([dim_date, special_dates], ignore_index=True)

    def create_screen_dimension(self):

        dim_screen = pd.DataFrame({
            'screen_id': [1, 2, 3, 4, 5, 6],
            'screen_name': ['Valor nulo', 'Valor fuera de intervalo', 'Valor fuera de lista', 
                            'Cadena no compuesta por dígitos ', 'Fecha con formato incorrecto', 
                            'Valor no único'],
            'screen_description': [None] * 6,
            'etl_module': [None] * 6
        })

        self.dim_screen = dim_screen

In [5]:
## SUBSYSTEM FOR DIMENSION MANAGEMENT
class AbstractDimensionManager(ABC):
    
    @abstractmethod
    def init_date_dimension(self):
        pass

class DimensionManager(AbstractDimensionManager):

    def __init__(self):
        self.special_dimension_manager = SpecialDimensionManager()

    def init_date_dimension(self):

        self.special_dimension_manager.create_date_dimension()
        dim_date = self.special_dimension_manager.dim_date

        conn = duckdb.connect("insurance_case.db")
        conn.sql("CREATE OR REPLACE TABLE silver.dim_date AS SELECT * FROM dim_date")
        conn.close()

In [7]:
## SUBSYSTEM FOR DATA CLEANSING
class AbstractValidator(ABC):

    def __init__(self):
        pass
   
    @abstractmethod
    def validate(self, **kwargs) -> bool:
        pass

class ValidatorIsMissingValue(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)       
        result = False

        if pd.isnull(value):
            result = True

        return result

class ValidatorIsOutOfBoundsValue(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        min_value = kwargs.get('min_value', None)
        max_value = kwargs.get('max_value', None)
        
        result = False
        if value < min_value or value > max_value:
            result = True

        return result
    
class ValidatorIsOutOfListValue(AbstractValidator):

    def validate(self, **kwargs):
        
        value = kwargs.get('value', None)
        valid_values = kwargs.get('valid_values', [])
        result = False

        if value not in valid_values:
            result = True

        return result
    
class ValidatorIsNotDigitString(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        number_of_digits = kwargs.get('number_of_digits', None)       
        result = False

        if not isinstance(value, str) or not value.isdigit():
            result = True

        if len(value) != number_of_digits:
            result = True

        return result
    
class ValidatorIsNotDateFormat(AbstractValidator):
    
    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        date_format = kwargs.get('date_format', None)  

        if pd.isnull(value):
            return False     

        try:
            datetime.datetime.strptime(value, date_format)
            result = False
        
        except ValueError:
            result = True
        
        return result

class ValidatorIsLowerThan(AbstractValidator):

    def validate(self, **kwargs):

        value_a = kwargs.get('value_a', None)
        value_b = kwargs.get('value_b', None) 
      
        result = False

        if pd.isnull(value_a) or pd.isnull(value_b):
            return result

        if value_a < value_b:
            result = True

        return result
    

#SCREENS
class AbstractValidationScreen(ABC):

    def __init__(self):
        pass

    @abstractmethod
    def apply_validation(self):
        pass

class ValidationScreenIsNotUnique(AbstractValidationScreen):

    def apply_validation(self, array):
        shape_01 = array.shape[0]
        shape_02 = array.nunique(dropna=True)

        if shape_01 != shape_02:
            raise Exception('Violation on uniqueness constraint detected.')

class ValidationScreenIsMisssingValue(AbstractValidationScreen):

    def apply_validation(self, array):
        validator = ValidatorIsMissingValue()
        results = array.apply(lambda x: validator.validate(value=x))
        return results
    
class ValidationScreenIsOutOfBoundsValue(AbstractValidationScreen):

    def apply_validation(self, array, min_value, max_value):
        validator = ValidatorIsOutOfBoundsValue()
        results = array.apply(lambda x: validator.validate(value=x, min_value=min_value, max_value=max_value))
        return results
    
class ValidationScreenIsOutOfListValue(AbstractValidationScreen):

    def apply_validation(self, array, valid_values):
        validator = ValidatorIsOutOfListValue()
        results = array.apply(lambda x: validator.validate(value=x, valid_values=valid_values))
        return results
    
class ValidationScreenIsNotDigitString(AbstractValidationScreen):
    
    def apply_validation(self, array, number_of_digits):
        validator = ValidatorIsNotDigitString()
        results = array.apply(lambda x: validator.validate(value=x, number_of_digits=number_of_digits))
        return results
    
class ValidationScreenIsNotDateFormat(AbstractValidationScreen):

    def apply_validation(self, array, date_format):
        validator = ValidatorIsNotDateFormat()
        results = array.apply(lambda x: validator.validate(value=x, date_format=date_format))
        return results

class ValidatorScreenIsLowerThan(AbstractValidationScreen):

    def apply_validation(self, array_a, array_b):
        validator = ValidatorIsLowerThan()
        results = pd.Series(zip(array_a, array_b)).apply(lambda x: validator.validate(value_a=x[0], value_b=x[1]))
        return results


#FACADE FOR SCREENS

class FacadeValidationScreens():

    def __init__(self):
        self.event_errors = []
        self.screen_is_not_unique = ValidationScreenIsNotUnique()
        self.screen_is_missing_value = ValidationScreenIsMisssingValue()
        self.screen_is_out_of_bounds_value = ValidationScreenIsOutOfBoundsValue()
        self.screen_is_out_of_list_value = ValidationScreenIsOutOfListValue()
        self.screen_is_not_digit_string = ValidationScreenIsNotDigitString()
        self.screen_is_not_date_format = ValidationScreenIsNotDateFormat()
        self.screen_is_lower_than = ValidatorScreenIsLowerThan()

    def setup(self, data, table_name, identifier):
        self.data = data
        self.table_name = table_name
        self.identifier = identifier

    def ensemble_error_event_detail(self, errors, column, screen_id):

        if errors.shape[0] == 0:
            return None
    
        utc_now = pd.Timestamp.utcnow().strftime('%Y-%m-%d %H:%M:%S')
        errors['error_event_id'] = 0
        errors['screen_id'] = screen_id
        errors['batch_id'] = 1
        errors['error_utc_timestamp'] = utc_now
        errors['table_name'] = self.table_name
        errors['column_name'] = column
        errors['record_identifier'] = errors[self.identifier]
        errors['original_value'] = errors[column]
        errors['replaced_value'] = None
        errors['error_condition'] = 'Sin Resolver'

        errors = errors[['error_event_id', 'batch_id', 'screen_id', 'error_utc_timestamp',
                         'table_name', 'column_name', 'record_identifier', 'original_value',
                         'replaced_value', 'error_condition']]
        
        self.event_errors.append(errors)

    def get_error_events_detail(self):
        
        if self.event_errors == []:
            return None
        
        else:
            return pd.concat(self.event_errors, ignore_index=True) 

    def apply_screen_is_not_unique(self, column):
        screen_id = 6
        self.screen_is_not_unique.apply_validation(self.data[column])     

    def apply_screen_is_missing_value(self, column):
        
        screen_id = 1        
        self.data['__screen__'] = self.screen_is_missing_value.apply_validation(self.data[column])
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_out_of_bounds_value(self, column, min_value, max_value):
        
        screen_id = 2        
        self.data['__screen__'] = self.screen_is_out_of_bounds_value.apply_validation(self.data[column], min_value, max_value)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_out_of_list_value(self, column, valid_values):
        
        screen_id = 3        
        self.data['__screen__'] = self.screen_is_out_of_list_value.apply_validation(self.data[column], valid_values)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_not_digit_string(self, column, number_of_digits):
        
        screen_id = 4        
        self.data['__screen__'] = self.screen_is_not_digit_string.apply_validation(self.data[column], number_of_digits)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_not_date_format(self, column, date_format):
        
        screen_id = 5        
        self.data['__screen__'] = self.screen_is_not_date_format.apply_validation(self.data[column], date_format)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_lower_than(self, column, reference_column):
        
        screen_id = 7        
        self.data['__screen__'] = self.screen_is_lower_than.apply_validation(self.data[column], self.data[reference_column])
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

In [ ]:
## SUBSYSTEM 06 FOR AUDIT DIMENSION ASSEMBLE
class AuditDimensionAssembler():

    def __init__(self, error_detail_table, table_name):
        self.error_detail_table = error_detail_table
        self.table_name = table_name
        self.etl_version = None

    def get_unsolved_rows(self):

        if self.error_detail_table is None:
            return []

        unsolved_rows = self.error_detail_table.loc[self.error_detail_table['error_condition'] == 'Sin Resolver']
        unsolved_rows = unsolved_rows.loc[unsolved_rows['table_name'] == self.table_name]
        unsolved_rows = unsolved_rows['record_identifier'].unique().tolist()

        return unsolved_rows

In [94]:
## SUBSYSTEM FOR DATA EXTRACTION

#SOURCE EXTRACTOR DEFINITION
class AbstractSourceExtractor(ABC):

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class AbstractFileExtractor(AbstractSourceExtractor):

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class AbstractDatabaseExtractor(AbstractSourceExtractor):

    @abstractmethod
    def connect(self):
        pass

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class GenericCsvExtractor(AbstractFileExtractor):

    def __init__(self):
        self.data = None
        self.facade_screens = FacadeValidationScreens()
        self.errors = None

    @abstractmethod
    def extract_data(self, file_path: str):
        pass

    @abstractmethod
    def screen_data(self):
        pass

    @abstractmethod
    def export_data():
        pass
    
class DiagnosesCsvExtractor(GenericCsvExtractor):

    def extract_data(self, file_path):

        path_pathologies = '/home/armando/git/insurance_case/datalake/raw/pathologies.csv'
        pathologies = pd.read_csv(path_pathologies, usecols=['code', 'id'])
        pathologies = pathologies.rename(columns={'code': 'cie_id', 'id': 'pathology_id'})

        print('Reading file: ', file_path)
        self.data = pd.read_csv(file_path)
        

        self.data = self.data.rename(columns={'consultation_id': 'consultation_id',
                                              'diagnosis': 'pathology_id'}) 
        self.data['consultation_diagnosis_id'] = np.arange(1, self.data.shape[0] + 1)

        self.data = self.data.merge(pathologies, how='inner', on='pathology_id')
        self.data = self.data.drop(columns=['pathology_id'])
    

    def screen_data(self):
        print('Screening data...')

        ##conn = duckdb.connect("insurance_case.db")
        conn = duckdb.connect("/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db")
        consultation_identifiers = conn.sql("SELECT consultation_id FROM silver.fact_consultation").df()
        cie_identifiers = conn.sql("SELECT cie_id FROM silver.dim_cie").df()
        conn.close()
        
        self.facade_screens.setup(data=self.data, table_name='consultation_diagnoses', identifier='consultation_diagnosis_id')
        
        #CHECK NULL VALUES
        columns = ['consultation_id', 'cie_id']
        for column in columns:
            self.facade_screens.apply_screen_is_missing_value(column)

        #CHECK UNIQUE VALUES
        self.facade_screens.apply_screen_is_not_unique('consultation_diagnosis_id')

        #CHECK OUT OF LIST VALUES
        self.facade_screens.apply_screen_is_out_of_list_value('consultation_id', consultation_identifiers['consultation_id'].tolist())
        self.facade_screens.apply_screen_is_out_of_list_value('cie_id', cie_identifiers['cie_id'].tolist())

        self.errors = self.facade_screens.get_error_events_detail()
        self.data = self.data.drop(columns=['__screen__'])

        #ADD AUDIT FACT COLUMN
        self.data['audit_passed'] = 'Sí'
        audit_dim_assembler = AuditDimensionAssembler(self.errors, 'consultation_diagnoses')
        unsolved_rows = audit_dim_assembler.get_unsolved_rows()
        self.data.loc[self.data['consultation_diagnosis_id'].isin(unsolved_rows), 'audit_passed'] = 'No'

    def export_data(self):
        pass

In [95]:
path = '/home/armando/git/insurance_case/datalake/preprocessed/consultation_diagnoses_dummy.csv'

extractor = DiagnosesCsvExtractor()
extractor.extract_data(path)
extractor.screen_data()

print(extractor.data.shape)
print(extractor.data.dtypes)
display(extractor.data.head(3))

Reading file:  /home/armando/git/insurance_case/datalake/preprocessed/consultation_diagnoses_dummy.csv
Screening data...
(432, 4)
consultation_id               int64
consultation_diagnosis_id     int64
cie_id                       object
audit_passed                 object
dtype: object

   consultation_id  consultation_diagnosis_id cie_id audit_passed
0                1                          1   M791           Sí
1                2                          2   I258           Sí
2                3                          3   Z000           Sí

In [96]:
display(extractor.data.loc[extractor.data['audit_passed'] == 'No'].head(3))

    consultation_id  consultation_diagnosis_id cie_id audit_passed
3                 4                          4    I10           No
6                 5                          7    I10           No
18               14                         19    I10           No

In [81]:
if extractor.errors is None:
    print('No errors detected.')
else:
    print(extractor.errors.shape)
    print(extractor.errors['original_value'].unique())
    display(extractor.errors.head(10))

(86, 10)
['I10' 'N40' 'C61' 'K30' 'E02' 'G20' 'F09' 'J00']

,error_event_id,batch_id,screen_id,error_utc_timestamp,table_name,column_name,record_identifier,original_value,replaced_value,error_condition
0,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,4,I10,None,Sin Resolver
1,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,7,I10,None,Sin Resolver
2,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,19,I10,None,Sin Resolver
3,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,24,I10,None,Sin Resolver
4,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,25,I10,None,Sin Resolver
5,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,26,I10,None,Sin Resolver
6,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,30,I10,None,Sin Resolver
7,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,31,N40,None,Sin Resolver
8,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,33,I10,None,Sin Resolver
9,0,1,3,2025-10-26 17:39:50,consultation_diagnoses,cie_id,38,I10,None,Sin Resolver

In [38]:
unsolved_rows = extractor.errors.loc[extractor.errors['error_condition'] == 'Sin Resolver']
unsolved_rows = unsolved_rows.loc[unsolved_rows['table_name'] == self.table_name]
#unsolved_rows = unsolved_rows['record_identifier'].unique().tolist()

display(unsolved_rows.head(10))

,error_event_id,batch_id,screen_id,error_utc_timestamp,table_name,column_name,record_identifier,original_value,replaced_value,error_condition
0,0,1,3,2025-10-26 16:28:40,claims,cie_id,xjm-23333,N40,None,Sin Resolver
1,0,1,3,2025-10-26 16:28:40,claims,cie_id,PhN-53226,R33,None,Sin Resolver
2,0,1,3,2025-10-26 16:28:40,claims,cie_id,cEx-28613,J91,None,Sin Resolver
3,0,1,3,2025-10-26 16:28:40,claims,cie_id,woJ-77662,R55,None,Sin Resolver

In [86]:
conn = duckdb.connect("/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db")

silver_incident_date = conn.sql("SELECT incident_date_id FROM silver.dim_incident_date").df()
silver_payment_date = conn.sql("SELECT payment_date_id FROM silver.dim_payment_date").df()
silver_first_expense_date = conn.sql("SELECT first_expense_date_id FROM silver.dim_first_expense_date").df()
silver_month_cont_date = conn.sql("SELECT month_cont_date_id FROM silver.dim_month_cont_date").df()
silver_certificate_id = conn.sql("SELECT surrogated_id AS surrogated_certificate_id, certificate_number FROM silver.dim_certificate").df()
silver_cie_id = conn.sql("SELECT surrogated_id AS surrogated_cie_id, cie_id FROM silver.dim_cie").df()
bronze_fact = conn.sql("SELECT * FROM bronze.fact_claim").df()
conn.close()

silver_fact = bronze_fact.copy()
silver_fact = silver_fact.loc[silver_fact['audit_passed'] == 'Sí']

shape_01 = silver_fact.shape[0]
print(silver_fact.shape)

silver_fact = silver_fact.merge(silver_incident_date, on='incident_date_id', how='inner')
silver_fact = silver_fact.drop(columns=['incident_date'])
print(silver_fact.shape)

silver_fact = silver_fact.merge(silver_payment_date, on='payment_date_id', how='inner')
silver_fact = silver_fact.drop(columns=['payment_date'])
print(silver_fact.shape)

silver_fact = silver_fact.merge(silver_first_expense_date, on='first_expense_date_id', how='inner')
silver_fact = silver_fact.drop(columns=['first_expense_date'])
print(silver_fact.shape)

silver_fact = silver_fact.merge(silver_month_cont_date, on='month_cont_date_id', how='inner')
silver_fact = silver_fact.drop(columns=['month_cont_date'])
print(silver_fact.shape)

silver_fact = silver_fact.merge(silver_certificate_id, on='certificate_number', how='inner')
silver_fact = silver_fact.drop(columns=['certificate_number'])
print(silver_fact.shape)

silver_fact = silver_fact.merge(silver_cie_id, on='cie_id', how='inner')
silver_fact = silver_fact.drop(columns=['cie_id'])
print(silver_fact.shape)

shape_02 = silver_fact.shape[0]

if not shape_01 == shape_02:
    raise Exception('Data loss detected during the fact merge process')

(47, 23)
(47, 22)
(47, 21)
(47, 20)
(47, 19)
(47, 19)
(47, 19)

In [ ]:
display(silver_fact)

In [97]:
conn = duckdb.connect("/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db")
#df = conn.sql("SELECT * FROM bronze.fact_claim").df()
#df = conn.sql("SELECT * FROM silver.dim_cie").df()
df = conn.sql("SELECT * FROM silver.bridge_consultation_diagnosis").df()
conn.close()

print(df.shape)
display(df.head(3))

(346, 2)

   consultation_id  surrogated_cie_id
0                1               5861
1                2               3824
2                3              13786

In [88]:
display(df.loc[df['audit_passed'] == 'No'].head(3))
display(df.loc[df['payment_date_id'] == -2].head(3))

,claim_id,state,cie_id,diagnosis,incident_date,payment_date,first_expense_date,ocurrido,payments,coinsurance,...,cve_mes,month_cont_date,payment_type,provider,certificate_number,incident_date_id,payment_date_id,first_expense_date_id,month_cont_date_id,audit_passed
11,xjm-23333,Valladolid,N40,HIPERPLASIA DE LA PROSTATA,2024-09-02,2024-09-11,2024-09-02,134493,159493.43,0.0,...,202409,2024-09-30,Pago Directo,Hospital del Mar,808816,20240902,20240911,20240902,20240930,No
26,PhN-53226,Guadalajara,R33,RETENCION DE ORINA,2025-03-27,2025-04-15,2025-03-27,18039,18039.30,0.0,...,202504,2025-04-30,Pago Directo,Instituto Médico,998371,20250327,20250415,20250327,20250430,No
38,cEx-28613,La Coruña,J91,DERRAME PLEURAL EN AFECCIONES CLASIFICADAS EN ...,2025-06-06,2025-06-20,2025-06-06,15965,15964.97,0.0,...,202506,2025-06-30,Pago Directo,Hospital Metropolitano,578807,20250606,20250620,20250606,20250630,No

,claim_id,state,cie_id,diagnosis,incident_date,payment_date,first_expense_date,ocurrido,payments,coinsurance,...,cve_mes,month_cont_date,payment_type,provider,certificate_number,incident_date_id,payment_date_id,first_expense_date_id,month_cont_date_id,audit_passed
8,aOL-65057,Palencia,D64,OTRAS ANEMIAS,2024-07-01,NaT,2024-07-01,11417,11416.99,0.0,...,202407,2024-07-31,Pago Directo,Clínica San Jorge,772653,20240701,-2,20240701,20240731,Sí

In [93]:
print('X0X'.rstrip('X'))

X0