In [1]:
import pandas as pd
import numpy as np
import datetime
import duckdb
from abc import ABC, abstractmethod

In [2]:
## SUBSYSTEM FOR DATAWAREHOUSE RESOURCES CREATION
class DatawarehouseResourcesCreator(ABC):
    
    def __init__(self):
        pass

    def init_schemas(self):
        conn = duckdb.connect("insurance_case.db")
        conn.sql('CREATE SCHEMA IF NOT EXISTS governance')
        conn.sql('CREATE SCHEMA IF NOT EXISTS silver')
        conn.sql("CREATE SCHEMA IF NOT EXISTS gold")
        conn.close()
    
    def init_error_tables(self):
        conn = duckdb.connect("insurance_case.db")

        conn.sql("""
            CREATE OR REPLACE TABLE governance.fact_error_event (
                error_event_id INTEGER,
                batch_id INTEGER
            )
        """)

        conn.sql("""
            CREATE OR REPLACE TABLE governance.fact_error_event_detail (
                error_event_id INTEGER,
                batch_id INTEGER,
                screen_id INTEGER,	
                error_utc_timestamp TIMESTAMP,
                table_name VARCHAR, 
                column_name VARCHAR,
                record_identifier INTEGER,
                original_value VARCHAR,
                replaced_value VARCHAR,
                error_condition VARCHAR
            )
        """)

        conn.close()

In [3]:
#datawarehouse_resources_creator = DatawarehouseResourcesCreator()
#datawarehouse_resources_creator.init_schemas()
#datawarehouse_resources_creator.init_error_tables()

In [2]:
## SUBSYSTEM FOR SPECIAL DIMENSIONS MANAGEMENT
class AbstractSpecialDimensionManager:
    
    @abstractmethod
    def create_date_dimension(self):
        pass

    @abstractmethod
    def create_screen_dimension(self):
        pass

class SpecialDimensionManager(AbstractSpecialDimensionManager):

    def __init__(self):
        self.dim_date = None
        self.dim_screen = None

    def create_date_dimension(self):
        
        array_dates = pd.date_range(start='1900-01-01', end='1900-01-01')
        array_dates = array_dates.append(pd.date_range(start='1925-01-01', end='2029-12-31'))
        array_dates = array_dates.append(pd.date_range(start='2200-01-01', end='2200-01-01'))

        dim_date = pd.DataFrame({'date_id': array_dates, 'date': array_dates})
        dim_date['date_name'] = dim_date['date'].dt.strftime('%Y-%m-%d')

        dim_date['day'] = dim_date['date'].dt.day
        dim_date['month'] = dim_date['date'].dt.month
        dim_date['year'] = dim_date['date'].dt.year
        dim_date['day_of_week'] = dim_date['date'].dt.dayofweek + 1
        dim_date['day_name'] = dim_date['date'].dt.day_name()
        dim_date['month_name'] = dim_date['date'].dt.month_name()
        dim_date['quarter'] = dim_date['date'].dt.quarter
        dim_date['weekday_indicator'] = np.where(dim_date['day_of_week'].isin([6, 7]), 'Fin de Semana', 'Entre Semana')
        dim_date['week_of_year'] = dim_date['date'].dt.isocalendar().week
        dim_date['is_end_of_month'] = np.where(dim_date['date'] == dim_date['date'] + pd.offsets.MonthEnd(0), True, False)
        dim_date['is_end_of_quarter'] = np.where(dim_date['date'] == dim_date['date'] + pd.offsets.QuarterEnd(0), True, False)
        dim_date['is_end_of_year'] = np.where(dim_date['date'] == dim_date['date'] + pd.offsets.YearEnd(0), True, False)

        dim_date['date_id'] = dim_date['date_id'].dt.strftime('%Y%m%d').astype(int)
        dim_date.loc[dim_date['day_name'] == 'Monday', 'day_name'] = 'Lunes'
        dim_date.loc[dim_date['day_name'] == 'Tuesday', 'day_name'] = 'Martes'
        dim_date.loc[dim_date['day_name'] == 'Wednesday', 'day_name'] = 'Miércoles'
        dim_date.loc[dim_date['day_name'] == 'Thursday', 'day_name'] = 'Jueves'
        dim_date.loc[dim_date['day_name'] == 'Friday', 'day_name'] = 'Viernes'
        dim_date.loc[dim_date['day_name'] == 'Saturday', 'day_name'] = 'Sábado'
        dim_date.loc[dim_date['day_name'] == 'Sunday', 'day_name'] = 'Domingo'
        dim_date.loc[dim_date['month_name'] == 'January', 'month_name'] = 'Enero'
        dim_date.loc[dim_date['month_name'] == 'February', 'month_name'] = 'Febrero'
        dim_date.loc[dim_date['month_name'] == 'March', 'month_name'] = 'Marzo'
        dim_date.loc[dim_date['month_name'] == 'April', 'month_name'] = 'Abril'
        dim_date.loc[dim_date['month_name'] == 'May', 'month_name'] = 'Mayo'
        dim_date.loc[dim_date['month_name'] == 'June', 'month_name'] = 'Junio'
        dim_date.loc[dim_date['month_name'] == 'July', 'month_name'] = 'Julio'
        dim_date.loc[dim_date['month_name'] == 'August', 'month_name'] = 'Agosto'
        dim_date.loc[dim_date['month_name'] == 'September', 'month_name'] = 'Septiembre'
        dim_date.loc[dim_date['month_name'] == 'October', 'month_name'] = 'Octubre'
        dim_date.loc[dim_date['month_name'] == 'November', 'month_name'] = 'Noviembre'
        dim_date.loc[dim_date['month_name'] == 'December', 'month_name'] = 'Diciembre'

        dim_date['quarter_name'] = 'T' + dim_date['quarter'].astype(str)
        dim_date['year_month'] = dim_date['year'].astype(str) + '-' + dim_date['month'].astype(str).str.zfill(2)
        dim_date['quarter_year'] = dim_date['quarter_name'] + ' ' + dim_date['year'].astype(str)

        dim_date['holiday_indicator'] = 'No Festivo'
        dim_date.loc[dim_date['date'].isin(['2025-01-01', '2025-02-05', '2025-03-21', '2025-05-01',
                                            '2025-09-16', '2025-11-20', '2025-12-25']), 'holiday_indicator'] = 'Festivo'

        special_dates = pd.DataFrame({'date_id': [-1, -2],
                                      'date': [None, None],
                                      'date_name': ['No Aplica', 'No Disponible'],
                                      'day': [0, 0],
                                      'month': [0, 0],
                                      'year': [0, 0],
                                      'day_of_week': [0, 0],
                                      'day_name': ['No Aplica', 'No Disponible'],
                                      'month_name': ['No Aplica', 'No Disponible'],
                                      'quarter': [0, 0],
                                      'weekday_indicator': ['No Aplica', 'No Disponible'],
                                      'week_of_year': [0, 0],
                                      'is_end_of_month': [False, False],
                                      'is_end_of_quarter': [False, False],
                                      'is_end_of_year': [False, False],
                                      'quarter_name': ['No Aplica', 'No Disponible'],
                                      'year_month': ['0000-00', '0000-00'],
                                      'quarter_year': ['No Aplica', 'No Disponible'],
                                      'holiday_indicator': ['No Aplica', 'No Disponible']})

        self.dim_date = pd.concat([dim_date, special_dates], ignore_index=True)

    def create_screen_dimension(self):

        dim_screen = pd.DataFrame({
            'screen_id': [1, 2, 3, 4, 5, 6],
            'screen_name': ['Valor nulo', 'Valor fuera de intervalo', 'Valor fuera de lista', 
                            'Cadena no compuesta por dígitos ', 'Fecha con formato incorrecto', 
                            'Valor no único'],
            'screen_description': [None] * 6,
            'etl_module': [None] * 6
        })

        self.dim_screen = dim_screen

In [3]:
## SUBSYSTEM FOR DIMENSION MANAGEMENT
class AbstractDimensionManager(ABC):
    
    @abstractmethod
    def init_date_dimension(self):
        pass

class DimensionManager(AbstractDimensionManager):

    def __init__(self):
        self.special_dimension_manager = SpecialDimensionManager()

    def init_date_dimension(self):

        self.special_dimension_manager.create_date_dimension()
        dim_date = self.special_dimension_manager.dim_date

        conn = duckdb.connect("insurance_case.db")
        conn.sql("CREATE OR REPLACE TABLE silver.dim_date AS SELECT * FROM dim_date")
        conn.close()

In [4]:
#dimension_manager = DimensionManager()
#dimension_manager.init_date_dimension()

In [5]:
terms = pd.read_csv('/home/armando/git/insurance_case/datalake/raw/terms_dummy.csv')
terms['fecha_inicio_vigencia'] = pd.to_datetime(terms['fecha_inicio_vigencia'], format='%Y-%m-%d')
terms['fecha_fin_periodo'] = pd.to_datetime(terms['fecha_fin_periodo'], format='%Y-%m-%d')
print(terms.shape)
display(terms.head(3))

(257, 4)

   id  certificate_number fecha_inicio_vigencia fecha_fin_periodo
0   1                  20            2021-01-20        2022-01-20
1   2                  25            2021-02-03        2022-02-03
2   3                  21            2021-02-16        2022-02-16

In [4]:
consultations = pd.read_csv('/home/armando/git/insurance_case/datalake/preprocessed/consultations_dummy.csv')
consultations['fecha_consulta'] = pd.to_datetime(consultations['fecha_consulta'], format='%Y-%m-%d')
print(consultations.shape)
display(consultations.head(3))

(350, 11)

,id,certificate_number,fecha_consulta,specialty,placed_by,day_note_consultation_observation,day_note_next_consultation_pending,day_note_needs_prescription_or_medical_order,patiend_goal,specialist_goal,pause_consultations
0,1,40,2024-08-21,general_medicine,286,La paciente se encuentra orientada en sus tres...,Mujer de la séptima década de la vida con los ...,none,Iniciar seguimiento médico,"Llenado de HC, plan de seguimiento",no
1,2,87,2025-02-15,geriatrics,176,✅ 78.800 kg en cita presencial de estudio de ...,"1️⃣ Verificar potasio sérico, se solicitó cont...",none,"Disminuir peso y grasa corporal, tener hábitos...",✅ Disminuir el riesgo cardiovascular mediante ...,no
2,3,42,2025-06-14,general_medicine,278,Ficha de identificación:\nNombre y cómo le gus...,- Completar esquema de vacunación\n- Realizar ...,none,Prevención primaria,Prevención primaria y secundaria. Validar indi...,no

In [5]:
diagnoses = pd.read_csv('/home/armando/git/insurance_case/datalake/preprocessed/consultation_diagnoses_dummy.csv')
print(diagnoses.shape)
display(diagnoses.head(3))

(432, 2)

   consultation_id  diagnosis
0                1       4917
1                2       3229
2                3      11797

In [6]:
pathologies = pd.read_csv('/home/armando/git/insurance_case/datalake/raw/pathologies.csv')
print(pathologies.shape)
display(pathologies.head(3))

(12423, 3)

   code  id                                               name
0  A000   1  COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO CH...
1  A001   2  COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO EL...
2  A009   3                             COLERA NO ESPECIFICADO

In [7]:
claims = pd.read_csv('/home/armando/git/insurance_case/datalake/raw/claims_dummy.csv')

#CONVERT FROM SPAIN NUMERIC FORMAT TO STANDARD FORMAT
for column in ['OCURRIDO', 'PAGOS', 'COASEGURO', 'IVAREC', 'DEDUCIBLE']:
    claims[column] = claims[column].astype(str)
    claims[column] = claims[column].str.replace('.', '', regex=False)
    claims[column] = claims[column].str.replace(',', '.', regex=False)
    claims[column] = pd.to_numeric(claims[column], errors='raise')

claims.loc[claims['FECHA_PAGO'] == '45491', 'FECHA_PAGO'] = None
claims['FECHA_OCURRIDO'] = pd.to_datetime(claims['FECHA_OCURRIDO'], format='%d/%m/%Y')
claims['FECHA_PAGO'] = pd.to_datetime(claims['FECHA_PAGO'], format='%d/%m/%Y')
claims['FECHA_PRIMERGASTO'] = pd.to_datetime(claims['FECHA_PRIMERGASTO'], format='%d/%m/%Y')
claims['MES_CONT'] = pd.to_datetime(claims['MES_CONT'], format='%d/%m/%Y')

print(claims.shape)
display(claims.head(3))

(51, 18)

,SINIESTRO,STATE,CIE10,DIAGNOSIS,FECHA_OCURRIDO,FECHA_PAGO,FECHA_PRIMERGASTO,OCURRIDO,PAGOS,COASEGURO,IVAREC,DEDUCIBLE,CAUSA,CVE_MES,MES_CONT,TIPO_PAGO,CLASF_PROV,NumCertificado
0,UcV-55067,Huesca,H33,DESPRENDIMIENTO Y DESGARRO DE LA RETINA,2023-09-22,2023-10-06,2023-09-22,43452,80176.71,10862.92,6952.28,25862.07,ENFERMEDAD,202310,2023-10-31,PAGO DIRECTO,Clínica Nuestra Señora,675725
1,Vvh-13843,Cuenca,D04.8,CARCINOMA IN SITU DE LA PIEL DE OTROS SITIOS E...,2023-12-20,2024-01-18,2023-12-20,-16568,23432.00,0.00,3749.11,0.00,ENFERMEDAD,202401,2024-01-31,PAGO DIRECTO,Hospital Metropolitano,577157
2,gZt-84016,Ciudad,L03.9,CELULITIS DE SITIO NO ESPECIFICADO,2024-01-28,2024-02-12,2024-01-28,8885,0.00,0.00,0.00,0.00,ENFERMEDAD,202402,2024-02-29,PAGO DIRECTO,Clínica San Jorge,704444

In [150]:
## SUBSYSTEM FOR DATA CLEANSING
class AbstractValidator(ABC):

    def __init__(self):
        pass
   
    @abstractmethod
    def validate(self, **kwargs) -> bool:
        pass

class ValidatorIsMissingValue(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)       
        result = False

        if pd.isnull(value):
            result = True

        return result

class ValidatorIsOutOfBoundsValue(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        min_value = kwargs.get('min_value', None)
        max_value = kwargs.get('max_value', None)
        
        result = False
        if value < min_value or value > max_value:
            result = True

        return result
    
class ValidatorIsOutOfListValue(AbstractValidator):

    def validate(self, **kwargs):
        
        value = kwargs.get('value', None)
        valid_values = kwargs.get('valid_values', [])
        result = False

        if value not in valid_values:
            result = True

        return result
    
class ValidatorIsNotDigitString(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        number_of_digits = kwargs.get('number_of_digits', None)       
        result = False

        if not isinstance(value, str) or not value.isdigit():
            result = True

        if len(value) != number_of_digits:
            result = True

        return result
    
class ValidatorIsNotDateFormat(AbstractValidator):
    
    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        date_format = kwargs.get('date_format', None)  

        if pd.isnull(value):
            return False     

        try:
            datetime.datetime.strptime(value, date_format)
            result = False
        
        except ValueError:
            result = True
        
        return result

class ValidatorIsLowerThan(AbstractValidator):

    def validate(self, **kwargs):

        value_a = kwargs.get('value_a', None)
        value_b = kwargs.get('value_b', None) 
      
        result = False

        if pd.isnull(value_a) or pd.isnull(value_b):
            return result

        if value_a < value_b:
            result = True

        return result
    

#SCREENS
class AbstractValidationScreen(ABC):

    def __init__(self):
        pass

    @abstractmethod
    def apply_validation(self):
        pass

class ValidationScreenIsNotUnique(AbstractValidationScreen):

    def apply_validation(self, array):
        shape_01 = array.shape[0]
        shape_02 = array.nunique(dropna=True)

        if shape_01 != shape_02:
            raise Exception('Violation on uniqueness constraint detected.')

class ValidationScreenIsMisssingValue(AbstractValidationScreen):

    def apply_validation(self, array):
        validator = ValidatorIsMissingValue()
        results = array.apply(lambda x: validator.validate(value=x))
        return results
    
class ValidationScreenIsOutOfBoundsValue(AbstractValidationScreen):

    def apply_validation(self, array, min_value, max_value):
        validator = ValidatorIsOutOfBoundsValue()
        results = array.apply(lambda x: validator.validate(value=x, min_value=min_value, max_value=max_value))
        return results
    
class ValidationScreenIsOutOfListValue(AbstractValidationScreen):

    def apply_validation(self, array, valid_values):
        validator = ValidatorIsOutOfListValue()
        results = array.apply(lambda x: validator.validate(value=x, valid_values=valid_values))
        return results
    
class ValidationScreenIsNotDigitString(AbstractValidationScreen):
    
    def apply_validation(self, array, number_of_digits):
        validator = ValidatorIsNotDigitString()
        results = array.apply(lambda x: validator.validate(value=x, number_of_digits=number_of_digits))
        return results
    
class ValidationScreenIsNotDateFormat(AbstractValidationScreen):

    def apply_validation(self, array, date_format):
        validator = ValidatorIsNotDateFormat()
        results = array.apply(lambda x: validator.validate(value=x, date_format=date_format))
        return results

class ValidatorScreenIsLowerThan(AbstractValidationScreen):

    def apply_validation(self, array_a, array_b):
        validator = ValidatorIsLowerThan()
        results = pd.Series(zip(array_a, array_b)).apply(lambda x: validator.validate(value_a=x[0], value_b=x[1]))
        return results


#FACADE FOR SCREENS

class FacadeValidationScreens():

    def __init__(self):
        self.event_errors = []
        self.screen_is_not_unique = ValidationScreenIsNotUnique()
        self.screen_is_missing_value = ValidationScreenIsMisssingValue()
        self.screen_is_out_of_bounds_value = ValidationScreenIsOutOfBoundsValue()
        self.screen_is_out_of_list_value = ValidationScreenIsOutOfListValue()
        self.screen_is_not_digit_string = ValidationScreenIsNotDigitString()
        self.screen_is_not_date_format = ValidationScreenIsNotDateFormat()
        self.screen_is_lower_than = ValidatorScreenIsLowerThan()

    def setup(self, data, table_name, identifier):
        self.data = data
        self.table_name = table_name
        self.identifier = identifier

    def ensemble_error_event_detail(self, errors, column, screen_id):

        if errors.shape[0] == 0:
            return None
    
        utc_now = pd.Timestamp.utcnow().strftime('%Y-%m-%d %H:%M:%S')
        errors['error_event_id'] = 0
        errors['screen_id'] = screen_id
        errors['batch_id'] = 1
        errors['error_utc_timestamp'] = utc_now
        errors['table_name'] = self.table_name
        errors['column_name'] = column
        errors['record_identifier'] = errors[self.identifier]
        errors['original_value'] = errors[column]
        errors['replaced_value'] = None
        errors['error_condition'] = 'Sin Resolver'

        errors = errors[['error_event_id', 'batch_id', 'screen_id', 'error_utc_timestamp',
                         'table_name', 'column_name', 'record_identifier', 'original_value',
                         'replaced_value', 'error_condition']]
        
        self.event_errors.append(errors)

    def get_error_events_detail(self):
        
        if self.event_errors == []:
            return None
        
        else:
            return pd.concat(self.event_errors, ignore_index=True) 

    def apply_screen_is_not_unique(self, column):
        screen_id = 6
        self.screen_is_not_unique.apply_validation(self.data[column])     

    def apply_screen_is_missing_value(self, column):
        
        screen_id = 1        
        self.data['__screen__'] = self.screen_is_missing_value.apply_validation(self.data[column])
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_out_of_bounds_value(self, column, min_value, max_value):
        
        screen_id = 2        
        self.data['__screen__'] = self.screen_is_out_of_bounds_value.apply_validation(self.data[column], min_value, max_value)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_out_of_list_value(self, column, valid_values):
        
        screen_id = 3        
        self.data['__screen__'] = self.screen_is_out_of_list_value.apply_validation(self.data[column], valid_values)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_not_digit_string(self, column, number_of_digits):
        
        screen_id = 4        
        self.data['__screen__'] = self.screen_is_not_digit_string.apply_validation(self.data[column], number_of_digits)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_not_date_format(self, column, date_format):
        
        screen_id = 5        
        self.data['__screen__'] = self.screen_is_not_date_format.apply_validation(self.data[column], date_format)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_lower_than(self, column, reference_column):
        
        screen_id = 7        
        self.data['__screen__'] = self.screen_is_lower_than.apply_validation(self.data[column], self.data[reference_column])
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

In [192]:
## SUBSYSTEM FOR DATA EXTRACTION

#SOURCE EXTRACTOR DEFINITION
class AbstractSourceExtractor(ABC):

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class AbstractFileExtractor(AbstractSourceExtractor):

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class AbstractDatabaseExtractor(AbstractSourceExtractor):

    @abstractmethod
    def connect(self):
        pass

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class GenericCsvExtractor(AbstractFileExtractor):

    def __init__(self):
        self.data = None
        self.facade_screens = FacadeValidationScreens()
        self.errors = None

    @abstractmethod
    def extract_data(self, file_path: str):
        pass

    @abstractmethod
    def screen_data(self):
        pass

    @abstractmethod
    def export_data():
        pass
    
class ClaimsCsvExtractor(GenericCsvExtractor):

    def extract_data(self, file_path):
        print('Reading file: ', file_path)
        self.data = pd.read_csv(file_path)
        self.data = self.data.rename(columns={'SINIESTRO': 'claim_id',
                                              'STATE': 'state',
                                              'CIE10': 'cie_id',
                                              'DIAGNOSIS': 'diagnosis',
                                              'FECHA_OCURRIDO': 'incident_date',
                                              'FECHA_PAGO': 'payment_date',
                                              'FECHA_PRIMERGASTO': 'first_expense_date',
                                              'OCURRIDO': 'ocurrido',
                                              'PAGOS': 'payments',
                                              'COASEGURO': 'coinsurance',
                                              'IVAREC': 'ivarec',
                                              'DEDUCIBLE': 'deductible',
                                              'CAUSA': 'incident_reason',
                                              'CVE_MES': 'cve_mes',
                                              'MES_CONT': 'month_cont_date',
                                              'TIPO_PAGO': 'payment_type',
                                              'CLASF_PROV': 'provider',
                                              'NumCertificado': 'certificate_number'                                             
                                              }) 

        self.data['certificate_number'] = self.data['certificate_number'].astype(str)
        self.data['cie_id'] = self.data['cie_id'].str.replace('.','', regex=False)

        self.data.loc[self.data['incident_reason'] == 'ENFERMEDAD', 'incident_reason'] = 'Enfermedad'
        self.data.loc[self.data['incident_reason'] == 'ACCIDENTE', 'incident_reason'] = 'Accidente'

        self.data.loc[self.data['payment_type'] == 'PAGO DIRECTO', 'payment_type'] = 'Pago Directo'

        self.data.loc[self.data['payment_date'] == '45491', 'payment_date'] = None

        for column in ['ocurrido', 'payments', 'coinsurance', 'ivarec', 'deductible']:
            self.data[column] = self.data[column].astype(str)
            self.data[column] = self.data[column].str.replace('.', '', regex=False)
            self.data[column] = self.data[column].str.replace(',', '.', regex=False)
            self.data[column] = pd.to_numeric(self.data[column], errors='raise')

    def screen_data(self):
        print('Screening data...')

        ##conn = duckdb.connect("insurance_case.db")
        conn = duckdb.connect("/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db")
        certificate_numbers = conn.sql("SELECT certificate_number FROM silver.dim_certificate").df()
        conn.close()
        
        self.facade_screens.setup(data=self.data, table_name='claims', identifier='claim_id')
        
        #CHECK NULL VALUES
        columns = ['state', 'cie_id', 'diagnosis', 'incident_date', 'payments', 'coinsurance',
                   'ivarec', 'deductible', 'incident_reason', 'cve_mes', 'month_cont_date', 'payment_type', 'provider', 'certificate_number']
        for column in columns:
            self.facade_screens.apply_screen_is_missing_value(column)

        #CHECK UNIQUE VALUES
        self.facade_screens.apply_screen_is_not_unique('claim_id')

        #CHECK NOT DIGIT STRING VALUES
        self.facade_screens.apply_screen_is_not_digit_string('certificate_number', 6)

        #CHECK NOT DATE FORMAT VALUES
        self.facade_screens.apply_screen_is_not_date_format('incident_date', '%d/%m/%Y')
        self.facade_screens.apply_screen_is_not_date_format('payment_date', '%d/%m/%Y')
        self.facade_screens.apply_screen_is_not_date_format('first_expense_date', '%d/%m/%Y')
        self.facade_screens.apply_screen_is_not_date_format('month_cont_date', '%d/%m/%Y')

        self.data['incident_date'] = pd.to_datetime(self.data['incident_date'], format='%d/%m/%Y')
        self.data['payment_date'] = pd.to_datetime(self.data['payment_date'], format='%d/%m/%Y')
        self.data['first_expense_date'] = pd.to_datetime(self.data['first_expense_date'], format='%d/%m/%Y')
        self.data['month_cont_date'] = pd.to_datetime(self.data['month_cont_date'], format='%d/%m/%Y')

        #CHECK OUT OF BOUNDS VALUES
        self.facade_screens.apply_screen_is_out_of_bounds_value('incident_date', pd.Timestamp('2020-01-01'), pd.Timestamp('2030-12-31'))
        self.facade_screens.apply_screen_is_out_of_bounds_value('payment_date', pd.Timestamp('2020-01-01'), pd.Timestamp('2030-12-31'))
        self.facade_screens.apply_screen_is_out_of_bounds_value('first_expense_date', pd.Timestamp('2020-01-01'), pd.Timestamp('2030-12-31'))
        self.facade_screens.apply_screen_is_out_of_bounds_value('month_cont_date', pd.Timestamp('2020-01-01'), pd.Timestamp('2030-12-31'))

        self.facade_screens.apply_screen_is_out_of_bounds_value('ocurrido', -1000000, 10000000)
        self.facade_screens.apply_screen_is_out_of_bounds_value('payments', 0, 10000000)
        self.facade_screens.apply_screen_is_out_of_bounds_value('coinsurance', 0, 1000000)
        self.facade_screens.apply_screen_is_out_of_bounds_value('ivarec', 0, 1000000)
        self.facade_screens.apply_screen_is_out_of_bounds_value('deductible', 0, 1000000)

        #CHECK CRONOLOGICAL ORDER
        self.facade_screens.apply_screen_is_lower_than('month_cont_date', 'payment_date')
        self.facade_screens.apply_screen_is_lower_than('payment_date', 'first_expense_date')
        self.facade_screens.apply_screen_is_lower_than('first_expense_date', 'incident_date')

        #CHECK OUT OF LIST VALUES
        self.facade_screens.apply_screen_is_out_of_list_value('certificate_number', certificate_numbers['certificate_number'].tolist())
        self.facade_screens.apply_screen_is_out_of_list_value('incident_reason', ['Enfermedad', 'Accidente'])
        self.facade_screens.apply_screen_is_out_of_list_value('payment_type', ['Pago Directo'])

        self.errors = self.facade_screens.get_error_events_detail()
        self.data = self.data.drop(columns=['__screen__'])

        #ADD AUDIT FACT COLUMN
        #self.data['audit_passed'] = 'Sí'
        #audit_dim_assembler = AuditDimensionAssembler(self.errors, 'term_dummy')
        #unsolved_rows = audit_dim_assembler.get_unsolved_rows()
        #self.data.loc[self.data['term_id'].isin(unsolved_rows), 'audit_passed'] = 'No'

    def export_data(self):
        pass

In [193]:
path = '/home/armando/git/insurance_case/datalake/raw/claims_dummy.csv'
extractor = ClaimsCsvExtractor()
extractor.extract_data(path)
extractor.screen_data()

print(extractor.data.shape)
print(extractor.data.dtypes)
display(extractor.data.head(3))

Reading file:  /home/armando/git/insurance_case/datalake/raw/claims_dummy.csv
Screening data...
(51, 18)
claim_id                      object
state                         object
cie_id                        object
diagnosis                     object
incident_date         datetime64[ns]
payment_date          datetime64[ns]
first_expense_date    datetime64[ns]
ocurrido                       int64
payments                     float64
coinsurance                  float64
ivarec                       float64
deductible                   float64
incident_reason               object
cve_mes                        int64
month_cont_date       datetime64[ns]
payment_type                  object
provider                      object
certificate_number            object
dtype: object

,claim_id,state,cie_id,diagnosis,incident_date,payment_date,first_expense_date,ocurrido,payments,coinsurance,ivarec,deductible,incident_reason,cve_mes,month_cont_date,payment_type,provider,certificate_number
0,UcV-55067,Huesca,H33,DESPRENDIMIENTO Y DESGARRO DE LA RETINA,2023-09-22,2023-10-06,2023-09-22,43452,80176.71,10862.92,6952.28,25862.07,Enfermedad,202310,2023-10-31,Pago Directo,Clínica Nuestra Señora,675725
1,Vvh-13843,Cuenca,D048,CARCINOMA IN SITU DE LA PIEL DE OTROS SITIOS E...,2023-12-20,2024-01-18,2023-12-20,-16568,23432.00,0.00,3749.11,0.00,Enfermedad,202401,2024-01-31,Pago Directo,Hospital Metropolitano,577157
2,gZt-84016,Ciudad,L039,CELULITIS DE SITIO NO ESPECIFICADO,2024-01-28,2024-02-12,2024-01-28,8885,0.00,0.00,0.00,0.00,Enfermedad,202402,2024-02-29,Pago Directo,Clínica San Jorge,704444

In [194]:
if extractor.errors is None:
    print('No errors detected.')
else:
    display(extractor.errors.head(10))

No errors detected.

In [ ]:

    



print(unsolved_rows)

In [33]:
conn = duckdb.connect("/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db")
dim_keys = conn.sql("SELECT surrogated_id AS surrogated_certificate_id, certificate_id FROM silver.dim_certificate").df()
conn.close()

print(dim_keys.shape)
display(dim_keys.head(3))

(100, 2)

   surrogated_certificate_id  certificate_id
0                          1               1
1                          2               2
2                          3               3

In [12]:
conn = duckdb.connect("/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db")
bronze_certificates = conn.sql("SELECT * FROM bronze.dim_certificates").df()
conn.close()

print(bronze_certificates.shape)
display(bronze_certificates.head(3))

(100, 8)

,certificate_id,name,email,age,city,birth_date,certificate_number,gender
0,1,Luisa Carrera Barroso,eutropiobravo@example.com,74,Zaragoza,1971-03-09,547829,M
1,2,Cristian Murcia,cesar23@example.net,55,Álava,1943-01-08,995112,M
2,3,Gala del Ortega,felipa93@example.com,63,Alicante,1947-01-29,138226,M

In [19]:
conn = duckdb.connect("insurance_case.db")
        silver_customer_birth_date = conn.sql("SELECT * FROM silver.dim_birth_date").df()
        bronze_dimension = conn.sql("SELECT * FROM bronze.dim_certificates").df()
        conn.close()

        silver_dimension = bronze_dimension.copy()
        silver_dimension['name'] = silver_dimension['name'].apply(lambda x: x[0:3] + '****')
        silver_dimension['email'] = silver_dimension['email'].apply(lambda x: '****' + x[x.find('@'):])

        silver_dimension = silver_dimension.merge(silver_customer_birth_date[['birth_date_id', 'date']],
                                                  left_on='birth_date',
                                                  right_on='date',
                                                  how='inner')

        if not silver_dimension.shape[0] == bronze_dimension.shape[0]:
            raise Exception('Data loss detected during the dimension merge process')

        keys = self.surrogate_key_generator.generate_surrogated_keys(silver_dimension.shape[0])
        silver_dimension['surrogated_id'] = keys

        columns_order = ['surrogated_id', 'certificate_id', 'name', 'email', 'age', 'city',
                        'gender', 'certificate_number', 'birth_date_id']
        self.silver_dimension = silver_dimension[columns_order]


print(silver_certificates.shape)
display(silver_certificates.head(3))

(100, 9)

,surrogated_id,certificate_id,name,email,age,city,gender,certificate_number,birth_date_id
0,1,1,Lui****,****@example.com,74,Zaragoza,M,547829,19710309
1,2,2,Cri****,****@example.net,55,Álava,M,995112,19430108
2,3,3,Gal****,****@example.com,63,Alicante,M,138226,19470129

In [22]:
conn = duckdb.connect("/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db")
silver_dimension = conn.sql("SELECT * FROM silver.dim_certificate").df()
conn.close()

print(silver_dimension.shape)
display(silver_dimension.head(3))

(100, 9)

,surrogated_id,certificate_id,name,email,age,city,gender,certificate_number,birth_date_id
0,1,1,Lui****,****@example.com,74,Zaragoza,M,547829,19710309
1,2,2,Cri****,****@example.net,55,Álava,M,995112,19430108
2,3,3,Gal****,****@example.com,63,Alicante,M,138226,19470129

In [185]:
#SUBSISTEMA 05 - FORMACION - ESQUEMA DE EVENTOS DE ERRORES
class AbtractErrorEventSchemaGenerator(ABC):

    @abstractmethod
    def generate_error_event_table(self):
        pass

    @abstractmethod
    def generate_error_detail_table(self):
        pass

class ErrorEventSchemaGenerator(AbtractErrorEventSchemaGenerator):

    def __init__(self, error_events_detail: pd.DataFrame):
        self.error_events_detail = error_events_detail

    def generate_error_event_table(self):
        error_event_table = self.error_events_detail[['screen_key', 'error_timestamp']].drop_duplicates().reset_index(drop=True)
        return error_event_table
    
    def generate_error_detail_table(self):
        return self.error_events_detail
    
error_event_schema_generator = ErrorEventSchemaGenerator(error_events_detail)
error_event_table = error_event_schema_generator.generate_error_event_table()
error_detail_table = error_event_schema_generator.generate_error_detail_table()

display(error_event_table)
display(error_detail_table)

NameError: name 'error_events_detail' is not defined

[158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257]