In [71]:
import pandas as pd
import numpy as np
import datetime
from abc import ABC, abstractmethod

(100, 8)

,id,nombre,email,edad,ciudad,fecha_nacimiento,numero_certificado,sexo
0,1,Luisa Carrera Barroso,eutropiobravo@example.com,74,Zaragoza,1971-03-09,547829,M
1,2,Cristian Murcia,cesar23@example.net,55,Álava,1943-01-08,995112,M
2,3,Gala del Ortega,felipa93@example.com,63,Alicante,1947-01-29,138226,M

In [3]:
terms = pd.read_csv('/home/armando/git/insurance_case/datalake/raw/terms_dummy.csv')
terms['fecha_inicio_vigencia'] = pd.to_datetime(terms['fecha_inicio_vigencia'], format='%Y-%m-%d')
terms['fecha_fin_periodo'] = pd.to_datetime(terms['fecha_fin_periodo'], format='%Y-%m-%d')
print(terms.shape)
display(terms.head(3))

(257, 4)

   id  certificate_number fecha_inicio_vigencia fecha_fin_periodo
0   1                  20            2021-01-20        2022-01-20
1   2                  25            2021-02-03        2022-02-03
2   3                  21            2021-02-16        2022-02-16

In [4]:
consultations = pd.read_csv('/home/armando/git/insurance_case/datalake/preprocessed/consultations_dummy.csv')
consultations['fecha_consulta'] = pd.to_datetime(consultations['fecha_consulta'], format='%Y-%m-%d')
print(consultations.shape)
display(consultations.head(3))

(350, 11)

,id,certificate_number,fecha_consulta,specialty,placed_by,day_note_consultation_observation,day_note_next_consultation_pending,day_note_needs_prescription_or_medical_order,patiend_goal,specialist_goal,pause_consultations
0,1,40,2024-08-21,general_medicine,286,La paciente se encuentra orientada en sus tres...,Mujer de la séptima década de la vida con los ...,none,Iniciar seguimiento médico,"Llenado de HC, plan de seguimiento",no
1,2,87,2025-02-15,geriatrics,176,✅ 78.800 kg en cita presencial de estudio de ...,"1️⃣ Verificar potasio sérico, se solicitó cont...",none,"Disminuir peso y grasa corporal, tener hábitos...",✅ Disminuir el riesgo cardiovascular mediante ...,no
2,3,42,2025-06-14,general_medicine,278,Ficha de identificación:\nNombre y cómo le gus...,- Completar esquema de vacunación\n- Realizar ...,none,Prevención primaria,Prevención primaria y secundaria. Validar indi...,no

In [5]:
diagnoses = pd.read_csv('/home/armando/git/insurance_case/datalake/preprocessed/consultation_diagnoses_dummy.csv')
print(diagnoses.shape)
display(diagnoses.head(3))

(432, 2)

   consultation_id  diagnosis
0                1       4917
1                2       3229
2                3      11797

In [6]:
pathologies = pd.read_csv('/home/armando/git/insurance_case/datalake/raw/pathologies.csv')
print(pathologies.shape)
display(pathologies.head(3))

(12423, 3)

   code  id                                               name
0  A000   1  COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO CH...
1  A001   2  COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO EL...
2  A009   3                             COLERA NO ESPECIFICADO

In [7]:
claims = pd.read_csv('/home/armando/git/insurance_case/datalake/raw/claims_dummy.csv')

#CONVERT FROM SPAIN NUMERIC FORMAT TO STANDARD FORMAT
for column in ['OCURRIDO', 'PAGOS', 'COASEGURO', 'IVAREC', 'DEDUCIBLE']:
    claims[column] = claims[column].astype(str)
    claims[column] = claims[column].str.replace('.', '', regex=False)
    claims[column] = claims[column].str.replace(',', '.', regex=False)
    claims[column] = pd.to_numeric(claims[column], errors='raise')

claims.loc[claims['FECHA_PAGO'] == '45491', 'FECHA_PAGO'] = None
claims['FECHA_OCURRIDO'] = pd.to_datetime(claims['FECHA_OCURRIDO'], format='%d/%m/%Y')
claims['FECHA_PAGO'] = pd.to_datetime(claims['FECHA_PAGO'], format='%d/%m/%Y')
claims['FECHA_PRIMERGASTO'] = pd.to_datetime(claims['FECHA_PRIMERGASTO'], format='%d/%m/%Y')
claims['MES_CONT'] = pd.to_datetime(claims['MES_CONT'], format='%d/%m/%Y')

print(claims.shape)
display(claims.head(3))

(51, 18)

,SINIESTRO,STATE,CIE10,DIAGNOSIS,FECHA_OCURRIDO,FECHA_PAGO,FECHA_PRIMERGASTO,OCURRIDO,PAGOS,COASEGURO,IVAREC,DEDUCIBLE,CAUSA,CVE_MES,MES_CONT,TIPO_PAGO,CLASF_PROV,NumCertificado
0,UcV-55067,Huesca,H33,DESPRENDIMIENTO Y DESGARRO DE LA RETINA,2023-09-22,2023-10-06,2023-09-22,43452,80176.71,10862.92,6952.28,25862.07,ENFERMEDAD,202310,2023-10-31,PAGO DIRECTO,Clínica Nuestra Señora,675725
1,Vvh-13843,Cuenca,D04.8,CARCINOMA IN SITU DE LA PIEL DE OTROS SITIOS E...,2023-12-20,2024-01-18,2023-12-20,-16568,23432.00,0.00,3749.11,0.00,ENFERMEDAD,202401,2024-01-31,PAGO DIRECTO,Hospital Metropolitano,577157
2,gZt-84016,Ciudad,L03.9,CELULITIS DE SITIO NO ESPECIFICADO,2024-01-28,2024-02-12,2024-01-28,8885,0.00,0.00,0.00,0.00,ENFERMEDAD,202402,2024-02-29,PAGO DIRECTO,Clínica San Jorge,704444

In [94]:
## SUBSYSTEM FOR DATA CLEANSING
class AbstractValidator(ABC):

    def __init__(self):
        pass
   
    @abstractmethod
    def validate(self, **kwargs) -> bool:
        pass

class ValidatorIsMissingValue(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)       
        result = False

        if pd.isnull(value):
            result = True

        return result

class ValidatorIsOutOfBoundsValue(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        min_value = kwargs.get('min_value', None)
        max_value = kwargs.get('max_value', None)
        
        result = False
        if value < min_value or value > max_value:
            result = True

        return result
    
class ValidatorIsOutOfListValue(AbstractValidator):

    def validate(self, **kwargs):
        
        value = kwargs.get('value', None)
        valid_values = kwargs.get('valid_values', [])
        result = False

        if value not in valid_values:
            result = True

        return result
    
class ValidatorIsNotDigitString(AbstractValidator):

    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        number_of_digits = kwargs.get('number_of_digits', None)       
        result = False

        if not isinstance(value, str) or not value.isdigit():
            result = True

        if len(value) != number_of_digits:
            result = True

        return result
    
class ValidatorIsNotDateFormat(AbstractValidator):
    
    def validate(self, **kwargs):

        value = kwargs.get('value', None)
        date_format = kwargs.get('date_format', None)       

        try:
            datetime.datetime.strptime(value, date_format)
            result = False
        
        except ValueError:
            result = True
        
        return result
    

#SCREENS
class AbstractValidationScreen(ABC):

    def __init__(self):
        pass

    @abstractmethod
    def apply_validation(self):
        pass

class ValidationScreenIsNotUnique(AbstractValidationScreen):

    def apply_validation(self, array):
        shape_01 = array.shape[0]
        shape_02 = array.nunique(dropna=True)

        if shape_01 != shape_02:
            raise Exception('Violation on uniqueness constraint detected.')

class ValidationScreenIsMisssingValue(AbstractValidationScreen):

    def apply_validation(self, array):
        validator = ValidatorIsMissingValue()
        results = array.apply(lambda x: validator.validate(value=x))
        return results
    
class ValidationScreenIsOutOfBoundsValue(AbstractValidationScreen):

    def apply_validation(self, array, min_value, max_value):
        validator = ValidatorIsOutOfBoundsValue()
        results = array.apply(lambda x: validator.validate(value=x, min_value=min_value, max_value=max_value))
        return results
    
class ValidationScreenIsOutOfListValue(AbstractValidationScreen):

    def apply_validation(self, array, valid_values):
        validator = ValidatorIsOutOfListValue()
        results = array.apply(lambda x: validator.validate(value=x, valid_values=valid_values))
        return results
    
class ValidationScreenIsNotDigitString(AbstractValidationScreen):
    
    def apply_validation(self, array, number_of_digits):
        validator = ValidatorIsNotDigitString()
        results = array.apply(lambda x: validator.validate(value=x, number_of_digits=number_of_digits))
        return results
    
class ValidationScreenIsNotDateFormat(AbstractValidationScreen):

    def apply_validation(self, array, date_format):
        validator = ValidatorIsNotDateFormat()
        results = array.apply(lambda x: validator.validate(value=x, date_format=date_format))
        return results
    
    
#class ValidationScreenHasIncongruentInverses(AbstractValidationScreen):

#    def apply_validation(self, array_a, array_b):

 #       results = pd.Series(zip(array_a, array_b)).apply(lambda x: self.validator.validate(value_a=x[0], value_b=x[1]))
 #       return results

class FacadeValidationScreens():

    def __init__(self):
        self.event_errors = []
        self.screen_is_not_unique = ValidationScreenIsNotUnique()
        self.screen_is_missing_value = ValidationScreenIsMisssingValue()
        self.screen_is_out_of_bounds_value = ValidationScreenIsOutOfBoundsValue()
        self.screen_is_out_of_list_value = ValidationScreenIsOutOfListValue()
        self.screen_is_not_digit_string = ValidationScreenIsNotDigitString()
        self.screen_is_not_date_format = ValidationScreenIsNotDateFormat()

    def setup(self, data, table_name, identifier):
        self.data = data
        self.table_name = table_name
        self.identifier = identifier

    def ensemble_error_event_detail(self, errors, column, screen_id):

        if errors.shape[0] == 0:
            return None
    
        errors['screen_id'] = screen_id
        errors['batch_id'] = 1
        errors['error_utc_timestamp'] = pd.Timestamp.utcnow()
        errors['table_name'] = self.table_name
        errors['column'] = column
        errors['record_identifier'] = errors[self.identifier]
        errors['value'] = errors[column]
        errors['error_condition'] = 'Sin Resolver'
        errors = errors[['screen_id', 'error_utc_timestamp', 'table_name', 'column', 'record_identifier', 'value', 'error_condition']]
        
        self.event_errors.append(errors)

    def get_error_events_detail(self):
        
        if self.event_errors == []:
            return None
        
        else:
            return pd.concat(self.event_errors, ignore_index=True) 

    def apply_screen_is_not_unique(self, column):
        self.screen_is_not_unique.apply_validation(self.data[column])     

    def apply_screen_is_missing_value(self, column):
        
        screen_id = 1        
        self.data['__screen__'] = self.screen_is_missing_value.apply_validation(self.data[column])
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_out_of_bounds_value(self, column, min_value, max_value):
        
        screen_id = 2        
        self.data['__screen__'] = self.screen_is_out_of_bounds_value.apply_validation(self.data[column], min_value, max_value)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_out_of_list_value(self, column, valid_values):
        
        screen_id = 3        
        self.data['__screen__'] = self.screen_is_out_of_list_value.apply_validation(self.data[column], valid_values)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_not_digit_string(self, column, number_of_digits):
        
        screen_id = 4        
        self.data['__screen__'] = self.screen_is_not_digit_string.apply_validation(self.data[column], number_of_digits)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

    def apply_screen_is_not_date_format(self, column, date_format):
        
        screen_id = 5        
        self.data['__screen__'] = self.screen_is_not_date_format.apply_validation(self.data[column], date_format)
        
        errors = self.data.loc[self.data['__screen__'] == True][[self.identifier, column]].copy()
        self.ensemble_error_event_detail(errors, column, screen_id)

In [99]:
## SUBSYSTEM FOR DATA EXTRACTION

#SOURCE EXTRACTOR DEFINITION
class AbstractSourceExtractor(ABC):

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class AbstractFileExtractor(AbstractSourceExtractor):

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class AbstractDatabaseExtractor(AbstractSourceExtractor):

    @abstractmethod
    def connect(self):
        pass

    @abstractmethod
    def extract_data(self):
        pass

    @abstractmethod
    def screen_data(self):
        pass

class GenericCsvExtractor(AbstractFileExtractor):

    def __init__(self):
        self.data = None
        self.facade_screens = FacadeValidationScreens()
        self.errors = None

    def extract_data(self, file_path: str):
        print('Reading file: ', file_path)
        self.data = pd.read_csv(file_path)

    @abstractmethod
    def screen_data(self):
        pass
    
class CertificatesCsvExtractor(GenericCsvExtractor):

    def extract_data(self, file_path):
        print('Reading file: ', file_path)
        self.data = pd.read_csv(file_path)
        self.data = self.data.rename(columns={'id': 'certificate_id', 
                                              'nombre': 'name',
                                              'email': 'email',
                                              'edad': 'age',
                                              'ciudad': 'city',
                                              'fecha_nacimiento': 'birth_date',
                                              'numero_certificado': 'certificate_number',
                                              'sexo': 'gender'})
        
        self.data['age'] = pd.to_numeric(self.data['age'], errors='raise')
        self.data['certificate_number'] = self.data['certificate_number'].astype(str)

    def screen_data(self):
        print('Screening data...')

        self.facade_screens.setup(data=self.data, table_name='certificate_dummy', identifier='certificate_id')
        
        #CHECK NULL VALUES
        columns = ['name', 'email', 'age', 'city', 'birth_date', 'certificate_number', 'gender']
        for column in columns:
            self.facade_screens.apply_screen_is_missing_value(column)

        #CHECK UNIQUE VALUES
        self.facade_screens.apply_screen_is_not_unique('certificate_id')
        self.facade_screens.apply_screen_is_not_unique('certificate_number')

        #CHECK NOT DIGIT STRING VALUES
        self.facade_screens.apply_screen_is_not_digit_string('certificate_number', 6)

        #CHECK NOT DATE FORMAT VALUES
        self.facade_screens.apply_screen_is_not_date_format('birth_date', '%Y-%m-%d')

        self.data['birth_date'] = pd.to_datetime(self.data['birth_date'], format='%Y-%m-%d')

        #CHECK OUT OF BOUNDS VALUES
        self.facade_screens.apply_screen_is_out_of_bounds_value('age', 0, 100)
        self.facade_screens.apply_screen_is_out_of_bounds_value('birth_date', pd.Timestamp('1925-01-01'), pd.Timestamp('2024-12-31'))

        #CHECK OUT OF LIST VALUES
        self.facade_screens.apply_screen_is_out_of_list_value('gender', ['M', 'F'])

        self.errors = self.facade_screens.get_error_events_detail()
        self.data = self.data.drop(columns=['__screen__'])

In [101]:
path = '/home/armando/git/insurance_case/datalake/raw/certificate_dummy.csv'
extractor = CertificatesCsvExtractor()
extractor.extract_data(path)
extractor.screen_data()

print(extractor.data.shape)
print(extractor.data.dtypes)
display(extractor.data.head(3))

Reading file:  /home/armando/git/insurance_case/datalake/raw/certificate_dummy.csv
Screening data...
(100, 8)
certificate_id                 int64
name                          object
email                         object
age                            int64
city                          object
birth_date            datetime64[ns]
certificate_number            object
gender                        object
dtype: object

,certificate_id,name,email,age,city,birth_date,certificate_number,gender
0,1,Luisa Carrera Barroso,eutropiobravo@example.com,74,Zaragoza,1971-03-09,547829,M
1,2,Cristian Murcia,cesar23@example.net,55,Álava,1943-01-08,995112,M
2,3,Gala del Ortega,felipa93@example.com,63,Alicante,1947-01-29,138226,M

In [79]:
""" 
#ESCRITORES DE ARCHIVOS
class AbstractFileWriter(ABC):

    @abstractmethod
    def write_file(self, data, file_path):
        pass

class JsonFileWriter(AbstractFileWriter):

    def write_file(self, data: dict, file_path: str):
        print('Simulando la escritura de datos JSON en:', file_path)
        print(data)

class CSVFileWriter(AbstractFileWriter):

    def write_file(self, data: pd.DataFrame, file_path: str):
        print('Simulando la escritura de datos CSV en:', file_path)
        print(data)

#CANALIZACIONES
class AbstractPipelineExtraction():

    @abstractmethod
    def execute(self, source_extractor: AbstractSourceExtractor, file_writer: AbstractFileWriter):
        pass

class PipelineFileExtraction(AbstractPipelineExtraction):

    def __init__(self, source_path: str, destination_path: str):
        self.source_path = source_path
        self.destination_path = destination_path
    
    def execute(self, source_extractor: AbstractFileExtractor, file_writer: AbstractFileWriter):
        source_extractor.extract_data(self.source_path)
        data = source_extractor.parse_data()
        file_writer.write_file(data, self.destination_path)

class PipelineDatabaseExtraction(AbstractPipelineExtraction):

    def __init__(self, connection_string: str, query: str, destination_path: str):
        self.connection_string = connection_string
        self.query = query
        self.destination_path = destination_path
    
    def execute(self, source_extractor: AbstractDatabaseExtractor, file_writer: AbstractFileWriter):
        source_extractor.connect(self.connection_string)
        source_extractor.extract_data(self.query)
        data = source_extractor.parse_data()
        file_writer.write_file(data, self.destination_path)


#EJECUCION DE CANALIZACIONES
json_extractor = GenericJsonExtractor()
csv_extractor = GenericCsvExtractor()
postgres_extractor = PostgreSqlExtractor()

json_writer = JsonFileWriter()
csv_writer = CSVFileWriter()

pipeline_01 = PipelineFileExtraction('/ruta/al/archivo.json', '/ruta/de/salida/archivo_pipeline_salida.json')
pipeline_01.execute(json_extractor, json_writer)

pipeline_02 = PipelineFileExtraction('/ruta/al/archivo.csv', '/ruta/de/salida/archivo_pipeline_salida.csv')
pipeline_02.execute(csv_extractor, csv_writer)

pipeline_03 = PipelineDatabaseExtraction('dbname=test user=postgres password=secret', 'SELECT * FROM productos;', '/ruta/de/salida/productos_pipeline_salida.csv')
pipeline_03.execute(postgres_extractor, csv_writer)
"""

" \n#ESCRITORES DE ARCHIVOS\nclass AbstractFileWriter(ABC):\n\n    @abstractmethod\n    def write_file(self, data, file_path):\n        pass\n\nclass JsonFileWriter(AbstractFileWriter):\n\n    def write_file(self, data: dict, file_path: str):\n        print('Simulando la escritura de datos JSON en:', file_path)\n        print(data)\n\nclass CSVFileWriter(AbstractFileWriter):\n\n    def write_file(self, data: pd.DataFrame, file_path: str):\n        print('Simulando la escritura de datos CSV en:', file_path)\n        print(data)\n\n#CANALIZACIONES\nclass AbstractPipelineExtraction():\n\n    @abstractmethod\n    def execute(self, source_extractor: AbstractSourceExtractor, file_writer: AbstractFileWriter):\n        pass\n\nclass PipelineFileExtraction(AbstractPipelineExtraction):\n\n    def __init__(self, source_path: str, destination_path: str):\n        self.source_path = source_path\n        self.destination_path = destination_path\n    \n    def execute(self, source_extractor: AbstractFileExtractor, file_writer: AbstractFileWriter):\n        source_extractor.extract_data(self.source_path)\n        data = source_extractor.parse_data()\n        file_writer.write_file(data, self.destination_path)\n\nclass PipelineDatabaseExtraction(AbstractPipelineExtraction):\n\n    def __init__(self, connection_string: str, query: str, destination_path: str):\n        self.connection_string = connection_string\n        self.query = query\n        self.destination_path = destination_path\n    \n    def execute(self, source_extractor: AbstractDatabaseExtractor, file_writer: AbstractFileWriter):\n        source_extractor.connect(self.connection_string)\n        source_extractor.extract_data(self.query)\n        data = source_extractor.parse_data()\n        file_writer.write_file(data, self.destination_path)\n\n\n#EJECUCION DE CANALIZACIONES\njson_extractor = GenericJsonExtractor()\ncsv_extractor = GenericCsvExtractor()\npostgres_extractor = PostgreSqlExtractor()\n\njson_writer = JsonFileWriter()\ncsv_writer = CSVFileWriter()\n\npipeline_01 = PipelineFileExtraction('/ruta/al/archivo.json', '/ruta/de/salida/archivo_pipeline_salida.json')\npipeline_01.execute(json_extractor, json_writer)\n\npipeline_02 = PipelineFileExtraction('/ruta/al/archivo.csv', '/ruta/de/salida/archivo_pipeline_salida.csv')\npipeline_02.execute(csv_extractor, csv_writer)\n\npipeline_03 = PipelineDatabaseExtraction('dbname=test user=postgres password=secret', 'SELECT * FROM productos;', '/ruta/de/salida/productos_pipeline_salida.csv')\npipeline_03.execute(postgres_extractor, csv_writer)\n"

In [ ]:
#SUBSISTEMA 05 - FORMACION - ESQUEMA DE EVENTOS DE ERRORES
class AbtractErrorEventSchemaGenerator(ABC):

    @abstractmethod
    def generate_error_event_table(self):
        pass

    @abstractmethod
    def generate_error_detail_table(self):
        pass

class ErrorEventSchemaGenerator(AbtractErrorEventSchemaGenerator):

    def __init__(self, error_events_detail: pd.DataFrame):
        self.error_events_detail = error_events_detail

    def generate_error_event_table(self):
        error_event_table = self.error_events_detail[['screen_key', 'error_timestamp']].drop_duplicates().reset_index(drop=True)
        return error_event_table
    
    def generate_error_detail_table(self):
        return self.error_events_detail
    
error_event_schema_generator = ErrorEventSchemaGenerator(error_events_detail)
error_event_table = error_event_schema_generator.generate_error_event_table()
error_detail_table = error_event_schema_generator.generate_error_detail_table()

display(error_event_table)
display(error_detail_table)

In [ ]:
#SUBSISTEMA 06 - FORMACION - ENSAMBLE DE DIMENSION DE AUDITORIA
class AbstractAuditDimensionAssembler(ABC):

    @abstractmethod
    def set_etl_version(self, version):
        pass

    @abstractmethod
    def get_audit_id(self):
        pass
    
    @abstractmethod
    def audit_row(self):
        pass

class AuditDimensionAssembler(AbstractAuditDimensionAssembler):

    def __init__(self, fact_table, error_detail_table):
        self.fact_table = fact_table
        self.error_detail_table = error_detail_table
        self.etl_version = None

    def set_etl_version(self, version):
        self.etl_version = version

    def audit_row(self, row: dict):

        has_row_missing_values = 'Falso'
        has_row_value_out_of_bounds = 'Falso'


        subset = self.error_detail_table.loc[self.error_detail_table['table_key'] == self.fact_table]
        subset = subset.loc[subset['record_identifier'] == row['id_currency_rate']]
        subset = subset.loc[subset['screen_key'] == 1]

        if subset.shape[0] > 0:
            has_row_missing_values = 'Verdadero'

        subset = self.error_detail_table.loc[self.error_detail_table['table_key'] == self.fact_table]
        subset = subset.loc[subset['record_identifier'] == row['id_currency_rate']]
        subset = subset.loc[subset['screen_key'] == 2]
        
        if subset.shape[0] > 0:
            has_row_value_out_of_bounds = 'Verdadero'

        result = {}
        result['etl_version'] = self.etl_version
        result['missing_indicator'] = has_row_missing_values
        result['out_of_bounds_indicator'] = has_row_value_out_of_bounds
        result['inputed_indicator'] = 'Falso'

        quality_approved = 'Verdadero'
        if has_row_missing_values == 'Verdadero' or has_row_value_out_of_bounds == 'Verdadero':
            quality_approved = 'Falso'

        result['quality_approved'] = quality_approved

        return result
    
    def get_audit_id(self, result):
        #SE DEBE COMBINAR CON EL SUBSISTEMA DE LLAVES SURROGADAS
        if result['quality_approved'] == 'Verdadero':
            return 1
        else:
            return 2
        
audit_dim_assembler = AuditDimensionAssembler('fact_currency_rates', error_detail_table)
audit_dim_assembler.set_etl_version('v0.0.1')

for index, row in fact_currency_rates.iterrows():
    audit_info = audit_dim_assembler.audit_row(row)
    audit_surrogated_key = audit_dim_assembler.get_audit_id(audit_info)
    print(audit_info)
    print('Llave surrogada de DIM audit: ', audit_surrogated_key)
    print('---')