In [2]:
import pandas as pd
import numpy as np
import datetime

import duckdb

In [16]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.execute("DROP VIEW silver.dim_birth_date")
results = conn.execute("DROP VIEW silver.dim_term_begin_date")
results = conn.execute("DROP VIEW silver.dim_term_end_date")
results = conn.execute("DROP VIEW silver.dim_consultation_date")
results = conn.execute("DROP VIEW silver.dim_incident_date")
results = conn.execute("DROP VIEW silver.dim_payment_date")
results = conn.execute("DROP VIEW silver.dim_first_expense_date")
results = conn.execute("DROP VIEW silver.dim_month_cont_date")
conn.close()

In [20]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.execute("DROP TABLE governance.dim_screen")
conn.close()

In [28]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.execute("DROP TABLE bronze.dim_certificate")
conn.close()

In [30]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SHOW ALL TABLES").df()
conn.close()

print(results.shape)
display(results)

(26, 6)

,database,schema,name,column_names,column_types,temporary
0,insurance_case,bronze,bridge_consultation_diagnosis,"[consultation_id, consultation_diagnosis_id, c...","[BIGINT, BIGINT, VARCHAR, VARCHAR]",False
1,insurance_case,bronze,dim_certificate,"[certificate_id, name, email, age, city, birth...","[BIGINT, VARCHAR, VARCHAR, BIGINT, VARCHAR, TI...",False
2,insurance_case,bronze,dim_cie,"[cie_id, cie_name]","[VARCHAR, VARCHAR]",False
3,insurance_case,bronze,fact_claim,"[claim_id, state, cie_id, diagnosis, incident_...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, TIMESTAMP...",False
4,insurance_case,bronze,fact_consultation,"[consultation_id, certificate_id, consultation...","[BIGINT, BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT...",False
5,insurance_case,bronze,fact_term,"[term_id, certificate_id, term_begin_date, ter...","[BIGINT, BIGINT, TIMESTAMP_NS, TIMESTAMP_NS, V...",False
6,insurance_case,gold,age_at_diagnosis,"[surrogated_certificate_id, consultation_id, c...","[BIGINT, BIGINT, VARCHAR, VARCHAR, TIMESTAMP_N...",False
7,insurance_case,gold,customer_interaction,"[surrogated_certificate_id, certificate_number...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
8,insurance_case,governance,dim_screen,"[screen_id, screen_type, screen_name, screen_d...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
9,insurance_case,governance,fact_error_event,"[error_event_id, batch_id]","[INTEGER, INTEGER]",False
10,insurance_case,governance,fact_error_event_detail,"[error_event_id, batch_id, screen_id, error_ut...","[INTEGER, INTEGER, INTEGER, TIMESTAMP, VARCHAR...",False
11,insurance_case,silver,bridge_consultation_diagnosis,"[consultation_id, surrogated_cie_id]","[BIGINT, BIGINT]",False
12,insurance_case,silver,dim_birth_date,"[birth_date_id, date, date_type, day, month, y...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
13,insurance_case,silver,dim_certificate,"[surrogated_id, certificate_id, name, email, a...","[BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT, VAR...",False
14,insurance_case,silver,dim_cie,"[surrogated_id, cie_id, cie_name]","[BIGINT, VARCHAR, VARCHAR]",False
15,insurance_case,silver,dim_consultation_date,"[consultation_date_id, date, date_type, day, m...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
16,insurance_case,silver,dim_date,"[date_id, date, date_type, day, month, year, d...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
17,insurance_case,silver,dim_first_expense_date,"[first_expense_date_id, date, date_type, day, ...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
18,insurance_case,silver,dim_incident_date,"[incident_date_id, date, date_type, day, month...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
19,insurance_case,silver,dim_month_cont_date,"[month_cont_date_id, date, date_type, day, mon...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
20,insurance_case,silver,dim_payment_date,"[payment_date_id, date, date_type, day, month,...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
21,insurance_case,silver,dim_term_begin_date,"[term_begin_date_id, date, date_type, day, mon...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
22,insurance_case,silver,dim_term_end_date,"[term_end_date_id, date, date_type, day, month...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
23,insurance_case,silver,fact_claim,"[claim_id, state, surrogated_cie_id, incident_...","[VARCHAR, VARCHAR, BIGINT, BIGINT, BIGINT, BIG...",False
24,insurance_case,silver,fact_consultation,"[consultation_id, surrogated_certificate_id, c...","[BIGINT, BIGINT, BIGINT, VARCHAR, BIGINT, VARC...",False
25,insurance_case,silver,fact_term,"[term_id, surrogated_certificate_id, term_begi...","[BIGINT, BIGINT, BIGINT, BIGINT, VARCHAR]",False

In [15]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.dim_date").df()
conn.close()

display(results.head(6))
display(results.tail(6))

,date_id,date,date_type,day,month,year,day_of_week,day_name,month_name,quarter,weekday_indicator,week_of_year,is_end_of_month,is_end_of_quarter,is_end_of_year,quarter_name,year_month,quarter_year,holiday_indicator
0,19000101,1900-01-01,Fecha Disponible,1,1,1900,1,Lunes,Enero,1,Entre Semana,1,False,False,False,T1,1900-01,T1 1900,No Festivo
1,19250101,1925-01-01,Fecha Disponible,1,1,1925,4,Jueves,Enero,1,Entre Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
2,19250102,1925-01-02,Fecha Disponible,2,1,1925,5,Viernes,Enero,1,Entre Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
3,19250103,1925-01-03,Fecha Disponible,3,1,1925,6,Sábado,Enero,1,Fin de Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
4,19250104,1925-01-04,Fecha Disponible,4,1,1925,7,Domingo,Enero,1,Fin de Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
5,19250105,1925-01-05,Fecha Disponible,5,1,1925,1,Lunes,Enero,1,Entre Semana,2,False,False,False,T1,1925-01,T1 1925,No Festivo

,date_id,date,date_type,day,month,year,day_of_week,day_name,month_name,quarter,weekday_indicator,week_of_year,is_end_of_month,is_end_of_quarter,is_end_of_year,quarter_name,year_month,quarter_year,holiday_indicator
38351,20291231,2029-12-31,Fecha Disponible,31,12,2029,1,Lunes,Diciembre,4,Entre Semana,1,True,True,True,T4,2029-12,T4 2029,No Festivo
38352,22000101,2200-01-01,Fecha Disponible,1,1,2200,3,Miércoles,Enero,1,Entre Semana,1,False,False,False,T1,2200-01,T1 2200,No Festivo
38353,-1,NaT,No Aplica,0,0,0,0,No Aplica,No Aplica,0,No Aplica,0,False,False,False,No Aplica,0000-00,No Aplica,No Aplica
38354,-2,NaT,No Disponible,0,0,0,0,No Disponible,No Disponible,0,No Disponible,0,False,False,False,No Disponible,0000-00,No Disponible,No Disponible
38355,-3,NaT,Por Definir,0,0,0,0,Por Definir,Por Definir,0,Por Definir,0,False,False,False,Por Definir,0000-00,Por Definir,Por Definir
38356,-4,NaT,Fecha Inválida,0,0,0,0,Fecha Inválida,Fecha Inválida,0,Fecha Inválida,0,False,False,False,Fecha Inválida,0000-00,Fecha Inválida,Fecha Inválida

In [23]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM governance.dim_screen").df()
conn.close()

display(results.head(10))

,screen_id,screen_type,screen_name,screen_description,etl_module
0,1,Columnar,Valor nulo,Valor nulo,v0.0.1
1,2,Columnar,Valor fuera de intervalo,Valor fuera de intervalo,v0.0.1
2,3,Estructural,Valor fuera de lista,Valor fuera de lista,v0.0.1
3,4,Columnar,Cadena no compuesta por dígitos,Cadena no compuesta por dígitos,v0.0.1
4,5,Columnar,Fecha con formato incorrecto,Fecha con formato incorrecto,v0.0.1
5,6,Estructural,Valor no único,Valor no único,v0.0.1
6,7,Negocio,Valor menor que otro valor,Valor menor que otro valor,v0.0.1

In [31]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM governance.fact_error_event").df()
conn.close()

display(results.head(10))

Empty DataFrame
Columns: [error_event_id, batch_id]
Index: []

In [32]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM governance.fact_error_event_detail").df()
conn.close()

display(results.head(10))

Empty DataFrame
Columns: [error_event_id, batch_id, screen_id, error_utc_timestamp, table_name, column_name, record_identifier, original_value, replaced_value, error_condition]
Index: []

In [34]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM bronze.dim_certificate").df()
conn.close()

print(results.shape)
display(results.head(10))

(100, 8)

,certificate_id,name,email,age,city,birth_date,certificate_number,gender
0,1,Luisa Carrera Barroso,eutropiobravo@example.com,74,Zaragoza,1971-03-09,547829,M
1,2,Cristian Murcia,cesar23@example.net,55,Álava,1943-01-08,995112,M
2,3,Gala del Ortega,felipa93@example.com,63,Alicante,1947-01-29,138226,M
3,4,Abraham Bejarano,roigmaricruz@example.com,68,Salamanca,1952-08-31,312154,F
4,5,María Dolores Mosquera-Barriga,tapiaafrica@example.org,40,Huelva,1941-04-26,647930,M
5,6,Segismundo Ripoll Bermúdez,pinamarino@example.net,71,Salamanca,1946-06-08,729300,F
6,7,Clotilde Valverde Casares,claudia77@example.net,53,Zaragoza,1944-10-12,819230,F
7,8,Amílcar España Salazar,adora51@example.org,46,Segovia,1975-05-10,925814,F
8,9,Reynaldo Gilabert Quintanilla,roselloisaura@example.com,67,Cádiz,1941-11-26,824060,F
9,10,Mamen Sáez Piña,antondionisia@example.com,51,Badajoz,1965-11-03,578807,F