In [2]:
import pandas as pd
import numpy as np
import datetime

import duckdb

## Drop Date Views

In [16]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.execute("DROP VIEW silver.dim_birth_date")
results = conn.execute("DROP VIEW silver.dim_term_begin_date")
results = conn.execute("DROP VIEW silver.dim_term_end_date")
results = conn.execute("DROP VIEW silver.dim_consultation_date")
results = conn.execute("DROP VIEW silver.dim_incident_date")
results = conn.execute("DROP VIEW silver.dim_payment_date")
results = conn.execute("DROP VIEW silver.dim_first_expense_date")
results = conn.execute("DROP VIEW silver.dim_month_cont_date")
conn.close()

## Drop Governance Tables

In [20]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.execute("DROP TABLE governance.dim_screen")
results = conn.execute("DROP TABLE governance.fact_error_event	")
results = conn.execute("DROP TABLE governance.fact_error_event_detail")
conn.close()

## Drop Insurance Tables

In [52]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')

results = conn.execute("DROP TABLE IF EXISTS bronze.dim_certificate")
results = conn.execute("DROP TABLE IF EXISTS bronze.dim_cie")
results = conn.execute("DROP TABLE IF EXISTS bronze.fact_term")
results = conn.execute("DROP TABLE IF EXISTS bronze.fact_consultation")
results = conn.execute("DROP TABLE IF EXISTS bronze.bridge_consultation_diagnosis")
results = conn.execute("DROP TABLE IF EXISTS bronze.fact_claim")

results = conn.execute("DROP TABLE IF EXISTS silver.dim_certificate")
results = conn.execute("DROP TABLE IF EXISTS silver.dim_cie")
results = conn.execute("DROP TABLE IF EXISTS silver.fact_term")
results = conn.execute("DROP TABLE IF EXISTS silver.fact_consultation")
results = conn.execute("DROP TABLE IF EXISTS silver.bridge_consultation_diagnosis")
results = conn.execute("DROP TABLE IF EXISTS silver.fact_claim")

conn.close()

## Drop Gold Tables

In [91]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')

results = conn.execute("DROP TABLE IF EXISTS gold.age_at_diagnosis")
results = conn.execute("DROP TABLE IF EXISTS gold.customer_interaction")

conn.close()

## List Tables

In [93]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SHOW ALL TABLES").df()
conn.close()

print(results.shape)
display(results)

(26, 6)

,database,schema,name,column_names,column_types,temporary
0,insurance_case,bronze,bridge_consultation_diagnosis,"[consultation_id, consultation_diagnosis_id, c...","[BIGINT, BIGINT, VARCHAR, VARCHAR]",False
1,insurance_case,bronze,dim_certificate,"[certificate_id, name, email, age, city, birth...","[BIGINT, VARCHAR, VARCHAR, BIGINT, VARCHAR, TI...",False
2,insurance_case,bronze,dim_cie,"[cie_id, cie_name]","[VARCHAR, VARCHAR]",False
3,insurance_case,bronze,fact_claim,"[claim_id, state, cie_id, diagnosis, incident_...","[VARCHAR, VARCHAR, VARCHAR, VARCHAR, TIMESTAMP...",False
4,insurance_case,bronze,fact_consultation,"[consultation_id, certificate_id, consultation...","[BIGINT, BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT...",False
5,insurance_case,bronze,fact_term,"[term_id, certificate_id, term_begin_date, ter...","[BIGINT, BIGINT, TIMESTAMP_NS, TIMESTAMP_NS, V...",False
6,insurance_case,gold,age_at_diagnosis,"[surrogated_certificate_id, consultation_id, c...","[BIGINT, BIGINT, VARCHAR, VARCHAR, TIMESTAMP_N...",False
7,insurance_case,gold,customer_interaction,"[surrogated_certificate_id, certificate_number...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, TIMESTAMP_NS]",False
8,insurance_case,governance,dim_screen,"[screen_id, screen_type, screen_name, screen_d...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR]",False
9,insurance_case,governance,fact_error_event,"[error_event_id, batch_id]","[INTEGER, INTEGER]",False
10,insurance_case,governance,fact_error_event_detail,"[error_event_id, batch_id, screen_id, error_ut...","[INTEGER, INTEGER, INTEGER, TIMESTAMP, VARCHAR...",False
11,insurance_case,silver,bridge_consultation_diagnosis,"[consultation_id, surrogated_cie_id]","[BIGINT, BIGINT]",False
12,insurance_case,silver,dim_birth_date,"[birth_date_id, date, date_type, day, month, y...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
13,insurance_case,silver,dim_certificate,"[surrogated_id, certificate_id, name, email, a...","[BIGINT, BIGINT, VARCHAR, VARCHAR, BIGINT, VAR...",False
14,insurance_case,silver,dim_cie,"[surrogated_id, cie_id, cie_name]","[BIGINT, VARCHAR, VARCHAR]",False
15,insurance_case,silver,dim_consultation_date,"[consultation_date_id, date, date_type, day, m...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
16,insurance_case,silver,dim_date,"[date_id, date, date_type, day, month, year, d...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
17,insurance_case,silver,dim_first_expense_date,"[first_expense_date_id, date, date_type, day, ...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
18,insurance_case,silver,dim_incident_date,"[incident_date_id, date, date_type, day, month...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
19,insurance_case,silver,dim_month_cont_date,"[month_cont_date_id, date, date_type, day, mon...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
20,insurance_case,silver,dim_payment_date,"[payment_date_id, date, date_type, day, month,...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
21,insurance_case,silver,dim_term_begin_date,"[term_begin_date_id, date, date_type, day, mon...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
22,insurance_case,silver,dim_term_end_date,"[term_end_date_id, date, date_type, day, month...","[BIGINT, TIMESTAMP_NS, VARCHAR, BIGINT, BIGINT...",False
23,insurance_case,silver,fact_claim,"[claim_id, state, surrogated_cie_id, incident_...","[VARCHAR, VARCHAR, BIGINT, BIGINT, BIGINT, BIG...",False
24,insurance_case,silver,fact_consultation,"[consultation_id, surrogated_certificate_id, c...","[BIGINT, BIGINT, BIGINT, VARCHAR, BIGINT, VARC...",False
25,insurance_case,silver,fact_term,"[term_id, surrogated_certificate_id, term_begi...","[BIGINT, BIGINT, BIGINT, BIGINT, VARCHAR]",False

## Dates

In [75]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.dim_date").df()
conn.close()

display(results.head(6))
display(results.tail(6))

,date_id,date,date_type,day,month,year,day_of_week,day_name,month_name,quarter,weekday_indicator,week_of_year,is_end_of_month,is_end_of_quarter,is_end_of_year,quarter_name,year_month,quarter_year,holiday_indicator
0,19000101,1900-01-01,Fecha Disponible,1,1,1900,1,Lunes,Enero,1,Entre Semana,1,False,False,False,T1,1900-01,T1 1900,No Festivo
1,19250101,1925-01-01,Fecha Disponible,1,1,1925,4,Jueves,Enero,1,Entre Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
2,19250102,1925-01-02,Fecha Disponible,2,1,1925,5,Viernes,Enero,1,Entre Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
3,19250103,1925-01-03,Fecha Disponible,3,1,1925,6,Sábado,Enero,1,Fin de Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
4,19250104,1925-01-04,Fecha Disponible,4,1,1925,7,Domingo,Enero,1,Fin de Semana,1,False,False,False,T1,1925-01,T1 1925,No Festivo
5,19250105,1925-01-05,Fecha Disponible,5,1,1925,1,Lunes,Enero,1,Entre Semana,2,False,False,False,T1,1925-01,T1 1925,No Festivo

,date_id,date,date_type,day,month,year,day_of_week,day_name,month_name,quarter,weekday_indicator,week_of_year,is_end_of_month,is_end_of_quarter,is_end_of_year,quarter_name,year_month,quarter_year,holiday_indicator
38351,20291231,2029-12-31,Fecha Disponible,31,12,2029,1,Lunes,Diciembre,4,Entre Semana,1,True,True,True,T4,2029-12,T4 2029,No Festivo
38352,22000101,2200-01-01,Fecha Disponible,1,1,2200,3,Miércoles,Enero,1,Entre Semana,1,False,False,False,T1,2200-01,T1 2200,No Festivo
38353,-1,NaT,No Aplica,0,0,0,0,No Aplica,No Aplica,0,No Aplica,0,False,False,False,No Aplica,0000-00,No Aplica,No Aplica
38354,-2,NaT,No Disponible,0,0,0,0,No Disponible,No Disponible,0,No Disponible,0,False,False,False,No Disponible,0000-00,No Disponible,No Disponible
38355,-3,NaT,Por Definir,0,0,0,0,Por Definir,Por Definir,0,Por Definir,0,False,False,False,Por Definir,0000-00,Por Definir,Por Definir
38356,-4,NaT,Fecha Inválida,0,0,0,0,Fecha Inválida,Fecha Inválida,0,Fecha Inválida,0,False,False,False,Fecha Inválida,0000-00,Fecha Inválida,Fecha Inválida

## Governance

In [76]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM governance.dim_screen").df()
conn.close()

display(results.head(10))

,screen_id,screen_type,screen_name,screen_description,etl_module
0,1,Columnar,Valor nulo,Valor nulo,v0.0.1
1,2,Columnar,Valor fuera de intervalo,Valor fuera de intervalo,v0.0.1
2,3,Estructural,Valor fuera de lista,Valor fuera de lista,v0.0.1
3,4,Columnar,Cadena no compuesta por dígitos,Cadena no compuesta por dígitos,v0.0.1
4,5,Columnar,Fecha con formato incorrecto,Fecha con formato incorrecto,v0.0.1
5,6,Estructural,Valor no único,Valor no único,v0.0.1
6,7,Negocio,Valor menor que otro valor,Valor menor que otro valor,v0.0.1

In [77]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM governance.fact_error_event").df()
conn.close()

display(results.head(10))

   error_event_id  batch_id
0               0         1
1               0         1
2               0         1
3               0         1

In [78]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM governance.fact_error_event_detail").df()
conn.close()

display(results.head(10))

,error_event_id,batch_id,screen_id,error_utc_timestamp,table_name,column_name,record_identifier,original_value,replaced_value,error_condition
0,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,4,I10,None,Sin Resolver
1,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,7,I10,None,Sin Resolver
2,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,19,I10,None,Sin Resolver
3,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,24,I10,None,Sin Resolver
4,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,25,I10,None,Sin Resolver
5,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,26,I10,None,Sin Resolver
6,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,30,I10,None,Sin Resolver
7,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,31,N40,None,Sin Resolver
8,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,33,I10,None,Sin Resolver
9,0,1,3,2025-10-31 18:13:03,consultation_diagnoses,cie_id,38,I10,None,Sin Resolver

## Certificates

In [79]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM bronze.dim_certificate").df()
conn.close()

print(results.shape)
display(results.head(3))

(100, 8)

,certificate_id,name,email,age,city,birth_date,certificate_number,gender
0,1,Luisa Carrera Barroso,eutropiobravo@example.com,74,Zaragoza,1971-03-09,547829,M
1,2,Cristian Murcia,cesar23@example.net,55,Álava,1943-01-08,995112,M
2,3,Gala del Ortega,felipa93@example.com,63,Alicante,1947-01-29,138226,M

In [80]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.dim_certificate").df()
conn.close()

print(results.shape)
display(results.head(3))

(100, 9)

,surrogated_id,certificate_id,name,email,age,city,gender,certificate_number,birth_date_id
0,1,1,Lui****,****@example.com,74,Zaragoza,M,547829,19710309
1,2,2,Cri****,****@example.net,55,Álava,M,995112,19430108
2,3,3,Gal****,****@example.com,63,Alicante,M,138226,19470129

## Cie

In [81]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM bronze.dim_cie").df()
conn.close()

print(results.shape)
display(results.head(3))

(14498, 2)

  cie_id                                           cie_name
0    A00                                             CÓLERA
1   A000  CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CH...
2   A001  CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL...

In [82]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.dim_cie").df()
conn.close()

print(results.shape)
display(results.head(3))

(14498, 3)

   surrogated_id cie_id                                           cie_name
0              1    A00                                             CÓLERA
1              2   A000  CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CH...
2              3   A001  CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL...

## Terms

In [83]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM bronze.fact_term").df()
conn.close()

print(results.shape)
display(results.head(3))

(257, 5)

   term_id  certificate_id term_begin_date term_end_date audit_passed
0        1              20      2021-01-20    2022-01-20           Sí
1        2              25      2021-02-03    2022-02-03           Sí
2        3              21      2021-02-16    2022-02-16           Sí

In [84]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.fact_term").df()
conn.close()

print(results.shape)
display(results.head(3))

(257, 5)

,term_id,surrogated_certificate_id,term_begin_date_id,term_end_date_id,audit_passed
0,1,20,20210120,20220120,Sí
1,2,25,20210203,20220203,Sí
2,3,21,20210216,20220216,Sí

## Consultations

In [85]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM bronze.fact_consultation").df()
conn.close()

print(results.shape)
display(results.head(3))

(350, 12)

,consultation_id,certificate_id,consultation_date,specialty,placed_by,consultation_observation,next_consultation_pending,prescription_or_medical_order,patient_goal,specialist_goal,pause_consultations,audit_passed
0,1,40,2024-08-21,Medicina General,286,La paciente se encuentra orientada en sus tres...,Mujer de la séptima década de la vida con los ...,Ninguno,Iniciar seguimiento médico,"Llenado de HC, plan de seguimiento",No,Sí
1,2,87,2025-02-15,Geriatría,176,✅ 78.800 kg en cita presencial de estudio de ...,"1️⃣ Verificar potasio sérico, se solicitó cont...",Ninguno,"Disminuir peso y grasa corporal, tener hábitos...",✅ Disminuir el riesgo cardiovascular mediante ...,No,Sí
2,3,42,2025-06-14,Medicina General,278,Ficha de identificación:\nNombre y cómo le gus...,- Completar esquema de vacunación\n- Realizar ...,Ninguno,Prevención primaria,Prevención primaria y secundaria. Validar indi...,No,Sí

In [86]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.fact_consultation").df()
conn.close()

print(results.shape)
display(results.head(3))

(350, 12)

,consultation_id,surrogated_certificate_id,consultation_date_id,specialty,placed_by,consultation_observation,next_consultation_pending,prescription_or_medical_order,patient_goal,specialist_goal,pause_consultations,audit_passed
0,1,40,20240821,Medicina General,286,La paciente se encuentra orientada en sus tres...,Mujer de la séptima década de la vida con los ...,Ninguno,Iniciar seguimiento médico,"Llenado de HC, plan de seguimiento",No,Sí
1,2,87,20250215,Geriatría,176,✅ 78.800 kg en cita presencial de estudio de ...,"1️⃣ Verificar potasio sérico, se solicitó cont...",Ninguno,"Disminuir peso y grasa corporal, tener hábitos...",✅ Disminuir el riesgo cardiovascular mediante ...,No,Sí
2,3,42,20250614,Medicina General,278,Ficha de identificación:\nNombre y cómo le gus...,- Completar esquema de vacunación\n- Realizar ...,Ninguno,Prevención primaria,Prevención primaria y secundaria. Validar indi...,No,Sí

## Diagnosis

In [87]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM bronze.bridge_consultation_diagnosis").df()
conn.close()

print(results.shape)
display(results.head(3))

(432, 4)

   consultation_id  consultation_diagnosis_id cie_id audit_passed
0                1                          1   M791           Sí
1                2                          2   I258           Sí
2                3                          3   Z000           Sí

In [88]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.bridge_consultation_diagnosis").df()
conn.close()

print(results.shape)
display(results.head(3))

(346, 2)

   consultation_id  surrogated_cie_id
0                1               5861
1                2               3824
2                3              13786

## Claims

In [89]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM bronze.fact_claim").df()
conn.close()

print(results.shape)
display(results.head(3))

(51, 23)

,claim_id,state,cie_id,diagnosis,incident_date,payment_date,first_expense_date,ocurrido,payments,coinsurance,...,cve_mes,month_cont_date,payment_type,provider,certificate_number,incident_date_id,payment_date_id,first_expense_date_id,month_cont_date_id,audit_passed
0,UcV-55067,Huesca,H33,DESPRENDIMIENTO Y DESGARRO DE LA RETINA,2023-09-22,2023-10-06,2023-09-22,43452,80176.71,10862.92,...,202310,2023-10-31,Pago Directo,Clínica Nuestra Señora,675725,20230922,20231006,20230922,20231031,Sí
1,Vvh-13843,Cuenca,D048,CARCINOMA IN SITU DE LA PIEL DE OTROS SITIOS E...,2023-12-20,2024-01-18,2023-12-20,-16568,23432.00,0.00,...,202401,2024-01-31,Pago Directo,Hospital Metropolitano,577157,20231220,20240118,20231220,20240131,Sí
2,gZt-84016,Ciudad,L039,CELULITIS DE SITIO NO ESPECIFICADO,2024-01-28,2024-02-12,2024-01-28,8885,0.00,0.00,...,202402,2024-02-29,Pago Directo,Clínica San Jorge,704444,20240128,20240212,20240128,20240229,Sí

In [90]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM silver.fact_claim").df()
conn.close()

print(results.shape)
display(results.head(3))

(47, 17)

,claim_id,state,surrogated_cie_id,incident_date_id,payment_date_id,first_expense_date_id,ocurrido,payments,coinsurance,ivarec,deductible,incident_reason,month_cont_date_id,payment_type,provider,surrogated_certificate_id,audit_passed
0,UcV-55067,Huesca,3448,20230922,20231006,20230922,43452,80176.71,10862.92,6952.28,25862.07,Enfermedad,20231031,Pago Directo,Clínica Nuestra Señora,53,Sí
1,Vvh-13843,Cuenca,1518,20231220,20240118,20231220,-16568,23432.00,0.00,3749.11,0.00,Enfermedad,20240131,Pago Directo,Hospital Metropolitano,39,Sí
2,gZt-84016,Ciudad,5001,20240128,20240212,20240128,8885,0.00,0.00,0.00,0.00,Enfermedad,20240229,Pago Directo,Clínica San Jorge,35,Sí

## Golden Tables

In [95]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM gold.customer_interaction").df()
conn.close()

print(results.shape)
display(results.head(30))

(1005, 5)

,surrogated_certificate_id,certificate_number,name,tipo_de_interaccion,fecha_de_interaccion
0,18,118716,Isa****,Inicio de Cobertura,2021-09-08
1,18,118716,Isa****,Consulta Médica,2021-12-06
2,18,118716,Isa****,Consulta Médica,2022-04-21
3,18,118716,Isa****,Inicio de Cobertura,2022-05-11
4,18,118716,Isa****,Consulta Médica,2022-07-09
5,18,118716,Isa****,Consulta Médica,2022-08-11
6,18,118716,Isa****,Fin de Cobertura,2022-09-08
7,18,118716,Isa****,Consulta Médica,2022-11-11
8,18,118716,Isa****,Fin de Cobertura,2023-05-11
9,18,118716,Isa****,Inicio de Cobertura,2023-12-29
10,18,118716,Isa****,Consulta Médica,2024-01-17
11,18,118716,Isa****,Inicio de Cobertura,2024-12-13
12,18,118716,Isa****,Consulta Médica,2024-12-20
13,18,118716,Isa****,Fin de Cobertura,2024-12-28
14,18,118716,Isa****,Consulta Médica,2025-05-24
15,18,118716,Isa****,Consulta Médica,2025-06-14
16,18,118716,Isa****,Consulta Médica,2025-07-05
17,18,118716,Isa****,Consulta Médica,2025-07-24
18,18,118716,Isa****,Fin de Cobertura,2025-12-13
19,46,123793,Hum****,Inicio de Cobertura,2022-11-12
20,46,123793,Hum****,Inicio de Cobertura,2023-08-02
21,46,123793,Hum****,Consulta Médica,2023-10-01
22,46,123793,Hum****,Fin de Cobertura,2023-11-12
23,46,123793,Hum****,Inicio de Cobertura,2024-04-30
24,46,123793,Hum****,Consulta Médica,2024-06-02
25,46,123793,Hum****,Fin de Cobertura,2024-08-01
26,46,123793,Hum****,Fin de Cobertura,2025-04-30
27,57,135265,Cri****,Inicio de Cobertura,2023-06-04
28,57,135265,Cri****,Consulta Médica,2023-06-10
29,57,135265,Cri****,Consulta Médica,2023-12-14

In [96]:
conn = duckdb.connect('/home/armando/git/insurance_case/dagster-quickstart/insurance_case.db')
results = conn.sql("SELECT * FROM gold.age_at_diagnosis").df()
conn.close()

print(results.shape)
display(results.head(30))

(346, 7)

,surrogated_certificate_id,consultation_id,cie_id,cie_name,birth_date,consultation_date,age_at_diagnosis
0,1,4,F412,TRASTORNO MIXTO DE ANSIEDAD Y DEPRESIÓN,1971-03-09,2021-08-27,50
1,1,268,E038,OTROS HIPOTIROIDISMOS ESPECIFICADOS,1971-03-09,2022-08-31,51
2,1,23,E119,"DIABETES MELLITUS TIPO 2, SIN MENCIÓN DE COMPL...",1971-03-09,2022-12-10,51
3,1,69,Z008,OTROS EXÁMENES GENERALES,1971-03-09,2022-06-30,51
4,1,220,C917,OTRAS LEUCEMIAS LINFOIDES,1971-03-09,2022-04-19,51
5,1,242,E109,"DIABETES MELLITUS TIPO 1, SIN MENCIÓN DE COMPL...",1971-03-09,2024-02-15,53
6,1,81,Z000,EXAMEN MÉDICO GENERAL,1971-03-09,2024-07-28,53
7,1,211,Z000,EXAMEN MÉDICO GENERAL,1971-03-09,2024-11-22,53
8,2,166,Z000,EXAMEN MÉDICO GENERAL,1943-01-08,2022-09-25,79
9,2,225,Z000,EXAMEN MÉDICO GENERAL,1943-01-08,2022-03-13,79
10,2,244,Z000,EXAMEN MÉDICO GENERAL,1943-01-08,2024-03-13,81
11,2,313,M810,"OSTEOPOROSIS POSTMENOPÁUSICA, SIN FRACTURA PAT...",1943-01-08,2024-02-26,81
12,2,315,Z000,EXAMEN MÉDICO GENERAL,1943-01-08,2025-08-30,82
13,3,260,E780,HIPERCOLESTEROLEMIA PURA,1947-01-29,2022-08-16,75
14,3,237,E119,"DIABETES MELLITUS TIPO 2, SIN MENCIÓN DE COMPL...",1947-01-29,2022-08-18,75
15,3,32,B029,HERPES ZOSTER SIN COMPLICACIONES,1947-01-29,2023-02-01,76
16,3,50,E039,"HIPOTIROIDISMO, NO ESPECIFICADO",1947-01-29,2023-08-07,76
17,3,281,E539,"DEFICIENCIA DE VITAMINA B, NO ESPECIFICADA",1947-01-29,2024-06-04,77
18,3,251,E112,"DIABETES MELLITUS TIPO 2, CON COMPLICACIONES R...",1947-01-29,2024-01-18,77
19,3,246,Z000,EXAMEN MÉDICO GENERAL,1947-01-29,2024-02-26,77
20,3,9,K590,CONSTIPACIÓN,1947-01-29,2025-03-13,78
21,4,311,E039,"HIPOTIROIDISMO, NO ESPECIFICADO",1952-08-31,2022-05-26,70
22,4,311,I499,"ARRITMIA CARDÍACA, NO ESPECIFICADA",1952-08-31,2022-05-26,70
23,4,82,M059,"ARTRITIS REUMATOIDEA SEROPOSITIVA, SIN OTRA ES...",1952-08-31,2022-11-25,70
24,4,151,R739,"HIPERGLICEMIA, NO ESPECIFICADA",1952-08-31,2022-04-13,70
25,4,311,E780,HIPERCOLESTEROLEMIA PURA,1952-08-31,2022-05-26,70
26,4,311,K589,SÍNDROME DEL COLON IRRITABLE SIN DIARREA,1952-08-31,2022-05-26,70
27,4,311,G500,NEURALGIA DEL TRIGÉMINO,1952-08-31,2022-05-26,70
28,4,51,Z000,EXAMEN MÉDICO GENERAL,1952-08-31,2024-10-14,72
29,5,215,E039,"HIPOTIROIDISMO, NO ESPECIFICADO",1941-04-26,2022-05-16,81